#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""补充 Combinatorics 分支的知识点"""

import json

# 读取现有数据
with open('data/core-nodes.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    nodes = data.get('nodes', [])

existing_ids = {n['id'] for n in nodes}

# 新的 Combinatorics 节点
new_combo_nodes = [
    # ========== 经典组合学 - 计数原理 ==========
    {"id": "combo_addition_rule", "type": "principle", "name": {"zh": "加法原理", "en": "Addition Rule"}, "description": {"zh": "互斥事件的计数：完成一件事有n类方法，每类方法分别有a1,a2,...,an种，则总方法数为Σai。", "en": ""}, "level": "junior", "branch": "combinatorics", "tags": ["初中", "数学"], "prerequisites": [], "difficulty": 2, "importance": 10, "estimated_minutes": 60},
    {"id": "combo_multiplication_rule", "type": "principle", "name": {"zh": "乘法原理", "en": "Multiplication Rule"}, "description": {"zh": "独立事件的计数：完成一件事需n个步骤，各步骤分别有a1,a2,...,an种方法，则总方法数为Πai。", "en": ""}, "level": "junior", "branch": "combinatorics", "tags": ["初中", "数学"], "prerequisites": [], "difficulty": 2, "importance": 10, "estimated_minutes": 60},
    {"id": "combo_circular_permutation", "type": "concept", "name": {"zh": "圆排列", "en": "Circular Permutation"}, "description": {"zh": "n个元素排成圆形的排列数：(n-1)!", "en": ""}, "level": "senior", "branch": "combinatorics", "tags": ["高中", "数学"], "prerequisites": ["s_sen57"], "difficulty": 3, "importance": 8, "estimated_minutes": 60},
    {"id": "combo_necklace_permutation", "type": "concept", "name": {"zh": "项链排列", "en": "Necklace Permutation"}, "description": {"zh": "将n颗珠子排成项链，考虑旋转和翻转对称", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_polya_counting"], "difficulty": 7, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_multiset_permutation", "type": "concept", "name": {"zh": "多重集排列", "en": "Permutation of Multisets"}, "description": {"zh": "有重复元素的排列数：n!/(n1!n2!...nk!)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["s_sen57"], "difficulty": 4, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_multiset_combination", "type": "concept", "name": {"zh": "多重集组合", "en": "Combination of Multisets"}, "description": {"zh": "从k种元素中取n个(可重复)的组合数：C(n+k-1,k-1)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["s_sen58"], "difficulty": 5, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_binomial_identity", "type": "formula", "name": {"zh": "二项式恒等式", "en": "Binomial Identities"}, "description": {"zh": "对称性、帕斯卡恒等式、范德蒙德恒等式、吸收恒等式等", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["s_sen60"], "difficulty": 5, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_vandermonde_identity", "type": "identity", "name": {"zh": "范德蒙德恒等式", "en": "Vandermonde Identity"}, "description": {"zh": "Σk C(r,k)C(s,n-k) = C(r+s,n)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_binomial_identity"], "difficulty": 6, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_bell_number", "type": "concept", "name": {"zh": "贝尔数", "en": "Bell Numbers"}, "description": {"zh": "n个元素所有划分的总数：B_n = Σ S(n,k)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_stirling_numbers"], "difficulty": 6, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_eulerian_number", "type": "concept", "name": {"zh": "欧拉数", "en": "Eulerian Numbers"}, "description": {"zh": "A(n,k)：n个排列中恰好有k个上升的排列数", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["s_sen57"], "difficulty": 7, "importance": 6, "estimated_minutes": 120},
    {"id": "combo_lah_number", "type": "concept", "name": {"zh": "Lah数", "en": "Lah Numbers"}, "description": {"zh": "将n个元素分成k个非空有序划分的数目", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_stirling_numbers"], "difficulty": 7, "importance": 6, "estimated_minutes": 90},
    {"id": "combo_partition_number", "type": "concept", "name": {"zh": "分拆数", "en": "Partition Numbers"}, "description": {"zh": "整数n的分拆数p(n)，五边形数定理", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_partitions"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_ordinary_gf", "type": "method", "name": {"zh": "普通生成函数", "en": "Ordinary Generating Function"}, "description": {"zh": "OGF: Σ a_n x^n，用于无标记结构计数", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_generating_function"], "difficulty": 6, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_exponential_gf", "type": "method", "name": {"zh": "指数生成函数", "en": "Exponential Generating Function"}, "description": {"zh": "EGF: Σ a_n x^n/n!，用于带标记结构计数", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_ordinary_gf"], "difficulty": 6, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_symbolic_method", "type": "method", "name": {"zh": "符号方法", "en": "Symbolic Method"}, "description": {"zh": "用组合类构造直接导出生成函数方程", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_exponential_gf"], "difficulty": 8, "importance": 9, "estimated_minutes": 240},
    {"id": "combo_lagrange_inversion", "type": "method", "name": {"zh": "拉格朗日反演", "en": "Lagrange Inversion"}, "description": {"zh": "从隐式定义的生成函数中提取系数", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_generating_function"], "difficulty": 8, "importance": 7, "estimated_minutes": 180},
    {"id": "combo_binomial_inversion", "type": "method", "name": {"zh": "二项式反演", "en": "Binomial Inversion"}, "description": {"zh": "a_n = Σ C(n,k) b_k iff b_n = Σ (-1)^{n-k} C(n,k) a_k", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_binomial_identity"], "difficulty": 6, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_mobius_inversion", "type": "method", "name": {"zh": "默比乌斯反演", "en": "Mobius Inversion"}, "description": {"zh": "偏序集上的一般反演，经典形式用于数论", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_binomial_inversion"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_graph_basics", "type": "concept", "name": {"zh": "图的基本概念", "en": "Graph Fundamentals"}, "description": {"zh": "图G=(V,E)：顶点集V、边集E。有向图/无向图、简单图/多重图、度数等", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学", "计算机科学"], "prerequisites": [], "difficulty": 4, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_handshaking_lemma", "type": "theorem", "name": {"zh": "握手引理", "en": "Handshaking Lemma"}, "description": {"zh": "所有顶点的度数之和等于两倍边数", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 3, "importance": 8, "estimated_minutes": 60},
    {"id": "combo_eulerian_path", "type": "theorem", "name": {"zh": "欧拉路径与回路", "en": "Eulerian Path"}, "description": {"zh": "欧拉回路存在条件：连通且所有顶点度数为偶", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 5, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_hamiltonian_path", "type": "theorem", "name": {"zh": "哈密顿路径", "en": "Hamiltonian Path"}, "description": {"zh": "经过每个顶点恰好一次的路径。狄拉克定理。NP完全", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 6, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_tree_properties", "type": "concept", "name": {"zh": "树的性质", "en": "Tree Properties"}, "description": {"zh": "树的等价定义：连通无回路、|E|=|V|-1、任意两点唯一路径", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 4, "importance": 9, "estimated_minutes": 90},
    {"id": "combo_cayley_formula", "type": "theorem", "name": {"zh": "凯莱公式", "en": "Cayley Formula"}, "description": {"zh": "n个标记顶点的树有n^{n-2}个", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_tree_properties"], "difficulty": 6, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_matrix_tree_theorem", "type": "theorem", "name": {"zh": "矩阵树定理", "en": "Matrix-Tree Theorem"}, "description": {"zh": "生成树数目等于拉普拉斯矩阵余子式行列式", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_tree_properties"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_spanning_tree", "type": "concept", "name": {"zh": "生成树", "en": "Spanning Tree"}, "description": {"zh": "包含图的所有顶点的树。Kruskal算法、Prim算法", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学", "计算机科学"], "prerequisites": ["combo_tree_properties"], "difficulty": 5, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_matching", "type": "concept", "name": {"zh": "匹配理论", "en": "Matching Theory"}, "description": {"zh": "两两无公共端点的边集。最大匹配、完美匹配", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 5, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_hall_marriage", "type": "theorem", "name": {"zh": "霍尔婚姻定理", "en": "Hall Marriage Theorem"}, "description": {"zh": "二部图存在完美匹配当且仅当任意k个左顶点至少与k个右顶点相邻", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_matching"], "difficulty": 6, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_konig_theorem", "type": "theorem", "name": {"zh": "克尼格定理", "en": "Konig Theorem"}, "description": {"zh": "二部图中最大匹配大小等于最小点覆盖大小", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_hall_marriage"], "difficulty": 7, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_tutte_theorem", "type": "theorem", "name": {"zh": "塔特定理", "en": "Tutte Theorem"}, "description": {"zh": "一般图存在完美匹配的刻画定理", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_matching"], "difficulty": 9, "importance": 9, "estimated_minutes": 240},
    {"id": "combo_vertex_cover", "type": "concept", "name": {"zh": "点覆盖与独立集", "en": "Vertex Cover"}, "description": {"zh": "点覆盖：覆盖所有边的顶点集。独立集：两两不相邻的顶点集", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 5, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_clique", "type": "concept", "name": {"zh": "团", "en": "Clique"}, "description": {"zh": "两两相邻的顶点集。团数ω(G)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_vertex_cover"], "difficulty": 5, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_graph_coloring", "type": "concept", "name": {"zh": "图染色", "en": "Graph Coloring"}, "description": {"zh": "相邻顶点不同色。色数χ(G)", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 5, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_brooks_theorem", "type": "theorem", "name": {"zh": "布鲁克斯定理", "en": "Brooks Theorem"}, "description": {"zh": "连通图(非完全图或奇环)的色数≤最大度Δ", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_graph_coloring"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_edge_coloring", "type": "concept", "name": {"zh": "边染色", "en": "Edge Coloring"}, "description": {"zh": "相邻边不同色。Vizing定理", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_graph_coloring"], "difficulty": 7, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_four_color", "type": "theorem", "name": {"zh": "四色定理", "en": "Four Color Theorem"}, "description": {"zh": "平面图可以用4种颜色染色", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_coloring"], "difficulty": 7, "importance": 10, "estimated_minutes": 180},
    {"id": "combo_perfect_graph", "type": "theorem", "name": {"zh": "完美图定理", "en": "Perfect Graph Theorem"}, "description": {"zh": "图G是完美图当且仅当其补图是完美图", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_graph_coloring"], "difficulty": 10, "importance": 8, "estimated_minutes": 240},
    {"id": "combo_planar_graph", "type": "concept", "name": {"zh": "平面图", "en": "Planar Graph"}, "description": {"zh": "可以嵌入平面且边不相交的图", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 5, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_euler_formula", "type": "formula", "name": {"zh": "欧拉公式", "en": "Euler Formula"}, "description": {"zh": "平面连通图：V - E + F = 2", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_planar_graph"], "difficulty": 5, "importance": 9, "estimated_minutes": 90},
    {"id": "combo_kuratowski_theorem", "type": "theorem", "name": {"zh": "库拉托夫斯基定理", "en": "Kuratowski Theorem"}, "description": {"zh": "图是平面图当且仅当不含K5或K3,3细分子图", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_planar_graph"], "difficulty": 8, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_dual_graph", "type": "concept", "name": {"zh": "对偶图", "en": "Dual Graph"}, "description": {"zh": "平面图G的对偶图G*：面对应顶点", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_planar_graph"], "difficulty": 5, "importance": 7, "estimated_minutes": 90},
    {"id": "combo_digraph", "type": "concept", "name": {"zh": "有向图", "en": "Directed Graph"}, "description": {"zh": "每条边有方向的图。入度、出度", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 4, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_dag_topol_sort", "type": "concept", "name": {"zh": "有向无环图与拓扑排序", "en": "DAG and Topological Sort"}, "description": {"zh": "不含回路的有向图的顶点排序", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学", "计算机科学"], "prerequisites": ["combo_digraph"], "difficulty": 5, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_tournament", "type": "concept", "name": {"zh": "竞赛图", "en": "Tournament"}, "description": {"zh": "每对顶点恰好有一条有向边的完全图", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_digraph"], "difficulty": 7, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_network_flow", "type": "concept", "name": {"zh": "网络流", "en": "Network Flow"}, "description": {"zh": "带容量限制的有向图上的流量问题", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学", "计算机科学"], "prerequisites": ["combo_digraph"], "difficulty": 6, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_max_flow_min_cut", "type": "theorem", "name": {"zh": "最大流最小割定理", "en": "Max-Flow Min-Cut"}, "description": {"zh": "最大流等于最小割的容量", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学", "计算机科学"], "prerequisites": ["combo_network_flow"], "difficulty": 7, "importance": 10, "estimated_minutes": 180},
    {"id": "combo_spectral_graph", "type": "concept", "name": {"zh": "谱图论", "en": "Spectral Graph Theory"}, "description": {"zh": "用图的矩阵特征值研究图性质", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 9, "importance": 8, "estimated_minutes": 240},
    {"id": "combo_turan_theorem", "type": "theorem", "name": {"zh": "图兰定理", "en": "Turan Theorem"}, "description": {"zh": "不含K_{r+1}的n顶点图最多边数由图兰图给出", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_extremal"], "difficulty": 8, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_erdos_stone", "type": "theorem", "name": {"zh": "埃尔多斯-斯通定理", "en": "Erdos-Stone Theorem"}, "description": {"zh": "一般图极值数的渐近刻画", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_turan_theorem"], "difficulty": 10, "importance": 8, "estimated_minutes": 240},
    {"id": "combo_ekr_theorem", "type": "theorem", "name": {"zh": "埃尔多斯-科-拉多定理", "en": "Erdos-Ko-Rado Theorem"}, "description": {"zh": "k-一致集族的交叉最大大小定理", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_extremal"], "difficulty": 9, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_sperner_theorem", "type": "theorem", "name": {"zh": "斯珀纳定理", "en": "Sperner Theorem"}, "description": {"zh": "反链的最大大小等于最大层的大小", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_extremal"], "difficulty": 8, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_expectation_method", "type": "method", "name": {"zh": "期望法", "en": "Expectation Method"}, "description": {"zh": "概率方法：计算随机变量期望来证明存在性", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_probabilistic"], "difficulty": 7, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_delete_argument", "type": "method", "name": {"zh": "删点法", "en": "Deletion Method"}, "description": {"zh": "通过删除不利元素构造满足条件的结构", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_probabilistic"], "difficulty": 8, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_lll", "type": "theorem", "name": {"zh": "洛瓦兹局部引理", "en": "Lovasz Local Lemma"}, "description": {"zh": "弱相关事件存在性证明的有力工具", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_probabilistic"], "difficulty": 10, "importance": 9, "estimated_minutes": 240},
    {"id": "combo_random_graph", "type": "concept", "name": {"zh": "随机图", "en": "Random Graphs"}, "description": {"zh": "G(n,p)模型，研究图的性质涌现", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_probabilistic"], "difficulty": 9, "importance": 8, "estimated_minutes": 240},
    {"id": "combo_matroid", "type": "concept", "name": {"zh": "拟阵", "en": "Matroid"}, "description": {"zh": "独立集的抽象公理系统：遗传性+交换性", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 9, "importance": 9, "estimated_minutes": 240},
    {"id": "combo_gaussian_binomial", "type": "formula", "name": {"zh": "高斯二项式系数", "en": "Gaussian Binomial Coefficient"}, "description": {"zh": "有限域向量空间的_qC(n,k)", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["s_sen60"], "difficulty": 8, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_bibd", "type": "concept", "name": {"zh": "平衡不完全区组设计", "en": "BIBD"}, "description": {"zh": "参数(v,b,r,k,λ)的区组设计", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_design_theory"], "difficulty": 8, "importance": 9, "estimated_minutes": 180},
    {"id": "combo_hadamard_matrix", "type": "concept", "name": {"zh": "阿达马矩阵", "en": "Hadamard Matrix"}, "description": {"zh": "元素为±1且两行正交的n阶方阵", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_bibd"], "difficulty": 8, "importance": 7, "estimated_minutes": 120},
    {"id": "combo_steiner_system", "type": "concept", "name": {"zh": "斯坦纳系统", "en": "Steiner System"}, "description": {"zh": "S(t,k,v)，Steiner三元系S(2,3,v)的存在条件", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_design_theory"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_finite_geometry", "type": "concept", "name": {"zh": "有限几何", "en": "Finite Geometry"}, "description": {"zh": "有限域上的射影空间PG(n,q)与仿射空间AG(n,q)", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_design_theory"], "difficulty": 8, "importance": 7, "estimated_minutes": 180},
    {"id": "combo_projective_plane", "type": "concept", "name": {"zh": "有限射影平面", "en": "Finite Projective Plane"}, "description": {"zh": "阶n的射影平面有n^2+n+1个点与线", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_finite_geometry"], "difficulty": 8, "importance": 8, "estimated_minutes": 120},
    {"id": "combo_pattern_avoidance", "type": "concept", "name": {"zh": "排列模式", "en": "Permutation Patterns"}, "description": {"zh": "避免模式的排列计数，Wilf-Stanley理论", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_enumerative"], "difficulty": 10, "importance": 7, "estimated_minutes": 240},
    {"id": "combo_bijective_combinatorics", "type": "concept", "name": {"zh": "双射组合", "en": "Bijective Combinatorics"}, "description": {"zh": "组合对象间的一一对应证明计数恒等式", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_enumerative"], "difficulty": 8, "importance": 7, "estimated_minutes": 180},
    {"id": "combo_simplicial_complex", "type": "concept", "name": {"zh": "单纯复形", "en": "Simplicial Complex"}, "description": {"zh": "组合拓扑中的关联结构", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_extremal"], "difficulty": 10, "importance": 7, "estimated_minutes": 180},
    {"id": "combo_sperner_lemma", "type": "lemma", "name": {"zh": "斯珀纳引理", "en": "Sperner Lemma"}, "description": {"zh": "组合不动点定理，用于Brouwer不动点定理的组合证明", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_sperner_theorem"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_asymptotic", "type": "method", "name": {"zh": "渐近计数", "en": "Asymptotic Counting"}, "description": {"zh": "斯特林公式、鞍点法等渐近分析方法", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_generating_function"], "difficulty": 10, "importance": 7, "estimated_minutes": 240},
    {"id": "combo_singular_analysis", "type": "method", "name": {"zh": "奇异分析", "en": "Singular Analysis"}, "description": {"zh": "从生成函数奇点提取渐近式，Flajolet-Odlyzko方法", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_asymptotic"], "difficulty": 10, "importance": 7, "estimated_minutes": 300},
    {"id": "combo_szemeredi", "type": "theorem", "name": {"zh": "塞梅洛迪定理", "en": "Szemerédi Theorem"}, "description": {"zh": "任意正密度的整数子集包含任意长等差数列", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_additive"], "difficulty": 10, "importance": 9, "estimated_minutes": 360},
    {"id": "combo_green_tao", "type": "theorem", "name": {"zh": "格林-陶定理", "en": "Green-Tao Theorem"}, "description": {"zh": "素数包含任意长等差数列", "en": ""}, "level": "phd", "branch": "combinatorics", "tags": ["博士", "数学"], "prerequisites": ["combo_szemeredi"], "difficulty": 10, "importance": 10, "estimated_minutes": 420},
    {"id": "combo_error_correcting", "type": "concept", "name": {"zh": "纠错码", "en": "Error-Correcting Codes"}, "description": {"zh": "线性码、循环码与组合设计的关系", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学", "计算机科学"], "prerequisites": ["combo_design_theory"], "difficulty": 8, "importance": 8, "estimated_minutes": 180},
    {"id": "combo_fibonacci", "type": "concept", "name": {"zh": "斐波那契数列", "en": "Fibonacci Numbers"}, "description": {"zh": "F_n = F_{n-1} + F_{n-2}，封闭形式比内公式", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_recurrence"], "difficulty": 5, "importance": 9, "estimated_minutes": 120},
    {"id": "combo_adjacency_matrix", "type": "concept", "name": {"zh": "邻接矩阵", "en": "Adjacency Matrix"}, "description": {"zh": "表示图的矩阵，用于图算法和谱分析", "en": ""}, "level": "undergrad", "branch": "combinatorics", "tags": ["本科", "数学"], "prerequisites": ["combo_graph_basics"], "difficulty": 4, "importance": 8, "estimated_minutes": 90},
    {"id": "combo_laplacian_matrix", "type": "concept", "name": {"zh": "拉普拉斯矩阵", "en": "Laplacian Matrix"}, "description": {"zh": "L = D - A，特征值与图的连通性相关", "en": ""}, "level": "master", "branch": "combinatorics", "tags": ["硕士", "数学"], "prerequisites": ["combo_adjacency_matrix"], "difficulty": 7, "importance": 8, "estimated_minutes": 120}
]

# 添加新节点
added = 0
for node in new_combo_nodes:
    if node["id"] not in existing_ids:
        nodes.append(node)
        existing_ids.add(node["id"])
        added += 1

data["nodes"] = nodes
with open("data/core-nodes.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"添加完成!")
print(f"  - 新增: {added} 个节点")
print(f"  - 总节点数: {len(nodes)}")

