#!/usr/bin/env python3
"""
数学知识图谱扩张脚本 — 分析/概率/数学物理
"""
import json, re

DATA_FILE = "/Users/jia/.qclaw/workspace/math-knowledge-graph/data/core-nodes.json"

def sid(text):
    s = re.sub(r'[^a-z0-9]', '', text.lower().replace(' ', '_'))
    return s[:70]

def node_exists(nodes, nid):
    return any(n['id'] == nid for n in nodes)

def make_node(nid, zhn, enn, branch, level, tags, kws,
               prereqs=None, difficulty=4, importance=7, minutes=60):
    if node_exists(nodes, nid):
        return None
    return {
        "id": nid, "type": "concept",
        "name": {"zh": zhn, "en": enn},
        "description": {"zh": zhn, "en": enn},
        "level": level, "branch": branch,
        "tags": tags,
        "prerequisites": list(prereqs) if prereqs else [],
        "difficulty": difficulty, "importance": importance,
        "estimated_minutes": minutes
    }

def add_node(nodes, n):
    if n:
        nodes.append(n)

def main():
    with open(DATA_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
    nodes = data['nodes']

    initial = len(nodes)
    existing_ids = {n['id'] for n in nodes}

    # ── 分析/泛函扩张 ──────────────────────────────
    b = "analysis"

    analysis_items = [
        # 实分析
        ("analysis_real_measure_theory", "测度论基础", "measure theory fundamentals",
         "undergrad", ["measure","Lebesgue measure","outer measure","Caratheodory",
          "measurable set","sigma-algebra","Borel sigma-algebra","completion"],
         ["analysis_real_introduction"], 5, 9, 90),
        ("analysis_measurable_functions", "可测函数", "measurable functions",
         "undergrad", ["measurable function","preimage measurable","simple function",
          "approximation by simple functions"," Lusin theorem"],
         ["analysis_real_measure_theory"], 4, 8, 60),
        ("analysis_lebesgue_integral", "Lebesgue积分", "Lebesgue integral",
         "undergrad", ["Lebesgue integral","Lebesgue integrable","L1 space",
          "absolute continuity of integral","Dominated convergence theorem"],
         ["analysis_measurable_functions"], 4, 9, 90),
        ("analysis_dominated_convergence", "支配收敛定理", "dominated convergence theorem",
         "undergrad", ["Dominated convergence theorem","DCT","Fatou lemma","Monotone convergence",
          "bounded convergence theorem","integral interchange limit"],
         ["analysis_lebesgue_integral"], 4, 9, 60),
        ("analysis_monotone_convergence", "单调收敛定理", "monotone convergence theorem",
         "undergrad", ["Monotone convergence theorem","MCT","non-negative functions",
          "increasing sequence"," Fatou lemma"],
         ["analysis_lebesgue_integral"], 3, 8, 45),
        ("analysis_fatou_lemma", "Fatou引理", "Fatou lemma",
         "undergrad", ["Fatou lemma","liminf of integrals","non-negative functions",
          "Fatou Lebesgue lemma","reverse Fatou"],
         ["analysis_lebesgue_integral"], 4, 8, 45),
        ("analysis_lp_spaces", "L^p空间", "Lp spaces",
         "undergrad", ["L^p space","Lp norm","Holder inequality","Minkowski inequality",
          "Riesz-Fischer theorem","completeness","conjugate exponent"],
         ["analysis_lebesgue_integral"], 4, 9, 90),
        ("analysis_l1_space", "L^1空间", "L1 space",
         "undergrad", ["L1 space","Lebesgue integrable functions","Riesz-Fischer",
          "Banach space L1","convolution in L1","approximate identity"],
         ["analysis_lp_spaces"], 4, 8, 60),
        ("analysis_l2_hilbert", "L^2空间与Hilbert空间", "L2 space and Hilbert spaces",
         "undergrad", ["L2 space","Hilbert space","inner product","orthogonality",
          "Riesz representation theorem Hilbert","completeness L2","Fourier series L2"],
         ["analysis_lp_spaces"], 4, 9, 90),
        ("analysis_holder_inequality", "Holder不等式", "Holder inequality",
         "undergrad", ["Holder inequality","1/p+1/q=1","conjugate exponents",
          "Lp norm","Minkowski inequality","Young inequality"],
         ["analysis_lp_spaces"], 4, 9, 60),
        ("analysis_minkowski_inequality", "Minkowski不等式", "Minkowski inequality",
         "undergrad", ["Minkowski inequality","triangle inequality for Lp","norm property",
          "vector valued Lp","sem norm"],
         ["analysis_lp_spaces"], 4, 8, 45),
        ("analysis_riesz_fischer", "Riesz-Fischer定理", "Riesz-Fischer theorem",
         "undergrad", ["Riesz-Fischer theorem","completeness of Lp","Cauchy sequence in Lp",
          "Lp is Banach","Lp convergence","norm convergence"],
         ["analysis_lp_spaces"], 4, 9, 60),
        ("analysis_ess_sup", "本性上确界", "essential supremum",
         "undergrad", ["essential supremum","essinf","essentially bounded",
          "L-infinity space","measurable essentially bounded","norm Linfty"],
         ["analysis_lp_spaces"], 4, 8, 45),
        ("analysis_almost_everywhere", "几乎处处收敛", "almost everywhere convergence",
         "undergrad", ["almost everywhere","ae convergence","convergence a.e.",
          "Egorov theorem"," Lusin theorem converse","null set"],
         ["analysis_lebesgue_integral"], 4, 8, 60),
        ("analysis_convergence_modes", "各种收敛模式", "modes of convergence",
         "undergrad", ["almost everywhere convergence","almost uniform convergence",
          "Lp convergence","convergence in measure","Lp implies subsequence a.e.",
          "uniform convergence","dominated convergence a.e."],
         ["analysis_almost_everywhere"], 4, 8, 60),
        ("analysis_egorov_theorem", "Egorov定理", "Egorov theorem",
         "undergrad", ["Egorov theorem","almost uniform convergence",
          "a.e. to uniform on set of small measure","approximation"],
         ["analysis_convergence_modes"], 4, 8, 45),
        ("analysis_lusin_theorem", "Lusin定理", "Lusin theorem",
         "undergrad", ["Lusin theorem","measurable on set of small measure zero",
          "continuous on large set","regularity of Lebesgue measure"],
         ["analysis_convergence_modes"], 4, 8, 45),
        ("analysis_signed_measures", "带号测度", "signed measures",
         "undergrad", ["signed measure","Jordan decomposition","positive and negative parts",
          "Hahn decomposition","variation of signed measure","total variation"],
         ["analysis_real_measure_theory"], 4, 8, 60),
        ("analysis_radon_nikodym", "Radon-Nikodym定理", "Radon-Nikodym theorem",
         "undergrad", ["Radon-Nikodym theorem","RN derivative","density","absolutely continuous",
          "Lebesgue decomposition","countably additive","RN derivative uniqueness"],
         ["analysis_signed_measures"], 5, 10, 90),
        ("analysis_conditional_expectation", "条件期望", "conditional expectation",
         "undergrad", ["conditional expectation","E[f|mathcal F]","sigma-algebra",
          "projection in L2","tower rule","measurability","existence RN"],
         ["analysis_radon_nikodym"], 5, 9, 90),
        ("analysis_product_measure", "乘积测度", "product measure",
         "undergrad", ["product measure","Fubini theorem","Tonelli theorem",
          "iterated integral","measurable rectangle","sigma-product"," uniqueness"],
         ["analysis_real_measure_theory"], 4, 9, 60),
        ("analysis_fubini_tonelli", "Fubini-Tonelli定理", "Fubini and Tonelli theorems",
         "undergrad", ["Fubini theorem","Tonelli theorem","iterated integral",
          "交换积分顺序","product measure"," Fubini failure"],
         ["analysis_product_measure"], 4, 9, 60),
        ("analysis_borel_cantelli", "Borel-Cantelli引理", "Borel-Cantelli lemmas",
         "undergrad", ["Borel-Cantelli lemma","BC1","BC2","limsup of sets",
          "measure zero","infinite trials","almost sure convergence"],
         ["analysis_real_measure_theory"], 4, 9, 45),
        ("analysis_stieltjes_integral", "Stieltjes积分", "Stieltjes integral",
         "undergrad", ["Stieltjes integral","Riemann-Stieltjes integral",
          "integration by parts","Lebesgue-Stieltjes","monotone function",
          "functions of bounded variation"],
         ["analysis_real_measure_theory"], 4, 8, 60),
        ("analysis_bv_functions", "有界变差函数", "functions of bounded variation",
         "undergrad", ["bounded variation","BV function","total variation",
          "Jordan decomposition","cantor function","differentiable a.e.",
          "absolute continuity"],
         ["analysis_stieltjes_integral"], 4, 8, 60),
        ("analysis_absolute_continuity", "绝对连续性", "absolute continuity",
         "undergrad", ["absolute continuity","ac function","singular function",
          "Lebesgue differentiation theorem","Fundamental theorem calculus",
          "BV and AC","singular continuous"],
         ["analysis_bv_functions"], 5, 9, 60),
        ("analysis_lebesgue_differentiation", "Lebesgue微分定理", "Lebesgue differentiation theorem",
         "undergrad", ["Lebesgue differentiation","almost everywhere derivative",
          "Vitali covering","density point","Lebesgue point","Hardy-Littlewood maximal"],
         ["analysis_absolute_continuity"], 5, 9, 90),
        ("analysis_hardy_littlewood_maximal", "Hardy-Littlewood极大函数", "Hardy-Littlewood maximal function",
         "undergrad", ["Hardy-Littlewood maximal","weak L1","maximal theorem",
          "Vitali covering argument","operator norm","Vitali covering lemma"],
         ["analysis_lebesgue_differentiation"], 5, 8, 60),
        ("analysis_cover_theorems", "Vitali覆盖定理", "Vitali covering theorems",
         "undergrad", ["Vitali covering","Vitali lemma"," Besicovitch covering",
          "covering lemma","differentiation of measures","maximal function"],
         ["analysis_lebesgue_differentiation"], 4, 8, 60),

        # 复分析
        ("analysis_complex_intro", "复数与复平面", "complex numbers and plane",
         "undergrad", ["complex plane","complex number","Argand diagram"," modulus","argument",
          "de Moivre","conjugate","polar form","Euler formula"],
         None, 3, 8, 60),
        ("analysis_complex_differentiability", "复可微与全纯", "complex differentiability and holomorphic",
         "undergrad", ["holomorphic","analytic complex","complex differentiable",
          "Cauchy-Riemann equations","analytic function","entier function",
          "differentiable at point"],
         ["analysis_complex_intro"], 4, 9, 60),
        ("analysis_cauchy_riemann", "Cauchy-Riemann方程", "Cauchy-Riemann equations",
         "undergrad", ["Cauchy-Riemann","CR equations","holomorphic necessary",
          "conjugate harmonic","harmonic function","u_x=v_y","u_y=-v_x"],
         ["analysis_complex_differentiability"], 4, 9, 60),
        ("analysis_power_series", "幂级数", "power series",
         "undergrad", ["power series","radius of convergence","analytic","uniform convergence",
          "Weierstrass M-test","differentiation of series","circle of convergence"],
         ["analysis_complex_intro"], 4, 9, 60),
        ("analysis_complex_integral", "复积分与Cauchy定理", "complex integration and Cauchy theorem",
         "undergrad", ["contour integral","Cauchy theorem","simply connected",
          "homotopy","deformation theorem","contour deformation","closed curve"],
         ["analysis_cauchy_riemann"], 5, 10, 90),
        ("analysis_cauchy_integral_formula", "Cauchy积分公式", "Cauchy integral formula",
         "undergrad", ["Cauchy integral formula","higher derivatives formula",
          "analytic everywhere inside contour","Cauchy's estimate","Morera theorem"],
         ["analysis_complex_integral"], 5, 10, 90),
        ("analysis_morera_theorem", "Morera定理", "Morera theorem",
         "undergrad", ["Morera theorem","converse of Cauchy theorem",
          "integral around closed contour zero implies holomorphic","Goursat theorem"],
         ["analysis_cauchy_integral_formula"], 4, 9, 45),
        ("analysis_liouville_theorem", "Liouville定理", "Liouville theorem",
         "undergrad", ["Liouville theorem","bounded entire function constant",
          "fundamental theorem of algebra proof","Picard theorem weak form"],
         ["analysis_cauchy_integral_formula"], 4, 9, 45),
        ("analysis_fundamental_theorem_algebra", "代数学基本定理（复分析证明）", "fundamental theorem of algebra via complex",
         "undergrad", ["fundamental theorem of algebra","Liouville theorem proof",
          "polynomial degree n n roots","complex analysis proof"],
         ["analysis_liouville_theorem"], 4, 8, 45),
        ("analysis_analytic_continuation", "解析延拓", "analytic continuation",
         "undergrad", ["analytic continuation","germ of function","monodromy theorem",
          "Riemann surface idea","power series continuation","natural boundary"],
         ["analysis_cauchy_integral_formula"], 5, 9, 90),
        ("analysis_schwarz_reflection", "Schwarz反射原理", "Schwarz reflection principle",
         "undergrad", ["Schwarz reflection","real boundary values","reflection across real axis",
          "harmonic conjugate","symmetry principle"],
         ["analysis_analytic_continuation"], 4, 8, 45),
        ("analysis_isolation_of_zeros", "零点的孤立性", "isolation of zeros",
         "undergrad", ["isolation of zeros","zeros of analytic function are isolated",
          "identity theorem","Removable singularity","pole","essential singularity"],
         ["analysis_cauchy_integral_formula"], 4, 9, 45),
        ("analysis_identity_theorem", "同一性定理", "identity theorem",
         "undergrad", ["identity theorem","analytic continuation uniqueness",
          "limit point of zeros","non-isolated zeros","uniqueness of analytic continuation"],
         ["analysis_isolation_of_zeros"], 4, 9, 45),
        ("analysis_laurent_series", "Laurent级数", "Laurent series",
         "undergrad", ["Laurent series","Laurent expansion","annulus","principal part",
          "convergent Laurent series","essential singularity Laurent"],
         ["analysis_cauchy_integral_formula"], 5, 9, 60),
        ("analysis_residue_theorem", "留数定理", "residue theorem",
         "undergrad", ["residue theorem","residue","Cauchy residue theorem",
          "countour integral via residues","winding number","argument principle"],
         ["analysis_laurent_series"], 5, 10, 90),
        ("analysis_argument_principle", "幅角原理", "argument principle",
         "undergrad", ["argument principle","winding number","count zeros minus poles",
          "Rouche theorem","open mapping theorem","change of argument"],
         ["analysis_residue_theorem"], 5, 9, 60),
        ("analysis_rouche_theorem", "Rouche定理", "Rouche theorem",
         "undergrad", ["Rouche theorem","zeros preserved under perturbation",
          "compare on boundary","application to roots","conformal mapping"],
         ["analysis_argument_principle"], 5, 9, 45),
        ("analysis_hurwitz_theorem", "Hurwitz定理", "Hurwitz theorem",
         "undergrad", ["Hurwitz theorem","uniform limit of holomorphic",
          "zeros converge to zeros","normal convergence","Hurwitz stability"],
         ["analysis_argument_principle"], 5, 8, 45),
        ("analysis_open_mapping_theorem", "开映射定理", "open mapping theorem",
         "undergrad", ["open mapping theorem","non-constant holomorphic open map",
          "open set maps to open set","maximum modulus principle","casorati-weierstrass"],
         ["analysis_argument_principle"], 5, 9, 60),
        ("analysis_maximum_modulus", "最大模原理", "maximum modulus principle",
         "undergrad", ["maximum modulus principle","maximum of |f| on compact set at boundary",
          "strong maximum modulus","Schwarz lemma boundary case","Phragmen-Lindelof"],
         ["analysis_open_mapping_theorem"], 4, 9, 60),
        ("analysis_schwarz_lemma", "Schwarz引理", "Schwarz lemma",
         "undergrad", ["Schwarz lemma","holomorphic from unit disk to itself",
          "fixing 0","|f(z)|<=|z|","Schwarz-Pick metric","automorphism disk"],
         ["analysis_maximum_modulus"], 5, 10, 60),
        ("analysis_schwarz_pick", "Schwarz-Pick度量", "Schwarz-Pick metric",
         "undergrad", ["Schwarz-Pick lemma","hyperbolic metric","Poincare disk",
          "Mobius transformation","distance invariance","isometry"],
         ["analysis_schwarz_lemma"], 5, 9, 60),
        ("analysis_bloch_theorem", "Bloch定理", "Bloch theorem",
         "undergrad", ["Bloch theorem","Bloch constant","univalent holomorphic",
          "injectivity radius","Landau constant","Koebe quarter theorem"],
         ["analysis_schwarz_lemma"], 5, 8, 60),
        ("analysis_riemann_mapping_theorem", "黎曼映射定理", "Riemann mapping theorem",
         "undergrad", ["Riemann mapping theorem","simply connected proper subset C biholomorphic to disk",
          "conformal map existence","boundary behavior","Caratheodory","Morrey"],
         ["analysis_open_mapping_theorem"], 6, 10, 120),
        ("analysis_harmonic_functions", "调和函数", "harmonic functions",
         "undergrad", ["harmonic function","Laplace equation","mean value property",
          "Poisson integral","Dirichlet problem"," Harnack principle"],
         ["analysis_cauchy_riemann"], 4, 9, 60),
        ("analysis_subharmonic", "次调和函数", "subharmonic functions",
         "undergrad", ["subharmonic","subharmonic function","mean value inequality",
          "plurisubharmonic","upper semicontinuous","harmonic majorant"],
         ["analysis_harmonic_functions"], 5, 8, 60),
        ("analysis_poisson_integral", "Poisson积分", "Poisson integral",
         "undergrad", ["Poisson integral","Poisson kernel","harmonic function from boundary data",
          "Dirichlet problem disk","Poisson representation","mean value property"],
         ["analysis_harmonic_functions"], 4, 9, 60),
        ("analysis_dirichlet_problem", "Dirichlet问题", "Dirichlet problem",
         "undergrad", ["Dirichlet problem","Laplace equation boundary values",
          "solution by Poisson integral"," Perriman method","variational method"],
         ["analysis_poisson_integral"], 5, 9, 90),
        ("analysis_picard_theorem", "Picard定理", "Picard theorems",
         "undergrad", ["Picard little theorem","essential singularity takes all values except one",
          "Picard great theorem","Picard Borner","Casorati-Weierstrass"],
         ["analysis_residue_theorem"], 6, 10, 90),
        ("analysis_normal_families", "正规族", "normal families",
         "undergrad", ["normal family","equicontinuous","Arzela-Ascoli","Montel theorem",
          "Montel theorem normal family","Vitali theorem","bounded implies normal"],
         ["analysis_argument_principle"], 5, 9, 90),
        ("analysis_montel_theorem", "Montel定理", "Montel theorem",
         "undergrad", ["Montel theorem","normal family bounded implies normal",
          "omitted values","normal family compactness","Arzela-Ascoli"],
         ["analysis_normal_families"], 5, 9, 60),
        ("analysis_conformal_mapping", "共形映射", "conformal mapping",
         "undergrad", ["conformal mapping","biholomorphic map","angle preserving",
          "Riemann mapping theorem","Schwarz-Christoffel","mapping of polygons"],
         ["analysis_riemann_mapping_theorem"], 5, 9, 90),
        ("analysis_schwarz_christoffel", "Schwarz-Christoffel公式", "Schwarz-Christoffel formula",
         "undergrad", ["Schwarz-Christoffel","conformal map from disk to polygon",
          "mapping of upper half-plane","integrate sqrt","polygon vertices"],
         ["analysis_conformal_mapping"], 5, 9, 90),
        ("analysis_rouche_poles", "Rouche定理在极点上的应用", "application of Rouche to poles",
         "undergrad", ["Rouche theorem poles","zeros and poles counting","meromorphic function",
          "winding number argument principle","Rouche on boundary"],
         ["analysis_rouche_theorem"], 4, 8, 60),
        ("analysis_elliptic_functions", "椭圆函数", "elliptic functions",
         "undergrad", ["elliptic function","doubly periodic meromorphic","Weierstrass elliptic",
          "Liouville theorem elliptic","meromorphic on fundamental parallelogram",
          "Weierstrass p-function","elliptic curve"],
         ["analysis_riemann_mapping_theorem"], 6, 9, 120),
        ("analysis_gamma_function", "Gamma函数", "Gamma function",
         "undergrad", ["Gamma function","Weierstrass product","Gamma function properties",
          "Euler reflection formula","Stirling formula","analytic continuation Gamma",
          "log Gamma","Gauss multiplication"],
         ["analysis_elliptic_functions"], 5, 9, 90),
        ("analysis_riemann_zeta_intro", "Riemann zeta函数简介", "introduction to Riemann zeta",
         "undergrad", ["Riemann zeta","zeta function","Euler product","Euler product for primes",
          "analytic continuation zeta","functional equation","Riemann hypothesis",
          "prime number theorem connection"],
         ["analysis_gamma_function"], 6, 9, 120),

        # Fourier分析
        ("analysis_fourier_series_intro", "Fourier级数简介", "Fourier series introduction",
         "undergrad", ["Fourier series","Fourier coefficients","trigonometric series",
          "convergence of Fourier series","Dirichlet kernel","Fejer kernel",
          "Gibbs phenomenon","pointwise convergence"],
         None, 4, 9, 90),
        ("analysis_fourier_coefficients", "Fourier系数", "Fourier coefficients",
         "undergrad", ["Fourier coefficients","a_n b_n","inner product on L2",
          "orthogonal trigonometric system","coefficient formula","Parseval"],
         ["analysis_fourier_series_intro"], 4, 9, 60),
        ("analysis_dirichlet_kernel", "Dirichlet核", "Dirichlet kernel",
         "undergrad", ["Dirichlet kernel","convolution with Dirichlet kernel",
          "Fourier partial sum","oscillatory integral","Dini test"],
         ["analysis_fourier_coefficients"], 4, 8, 60),
        ("analysis_fejer_kernel", "Fejer核", "Fejer kernel",
         "undergrad", ["Fejer kernel","Cesàro means of Fourier series",
          "uniform convergence of Fejer means","Fejer theorem",
          "positive kernel","approximate identity"],
         ["analysis_dirichlet_kernel"], 4, 9, 60),
        ("analysis_parseval_identity", "Parseval恒等式", "Parseval identity",
         "undergrad", ["Parseval identity","Fourier series L2 energy",
          "Plancherel theorem for Fourier series","Bessel inequality",
          "completeness of trigonometric system"],
         ["analysis_fejer_kernel"], 4, 9, 60),
        ("analysis_pointwise_convergence_fourier", "Fourier级数的点态收敛", "pointwise convergence of Fourier series",
         "undergrad", ["Dini test","Dirichlet test","Jordan test","Lebesgue test",
          " Carleson theorem","almost everywhere convergence","Lusin conjecture"],
         ["analysis_dirichlet_kernel"], 5, 9, 90),
        ("analysis_fourier_transform_real", "Fourier变换（实数）", "Fourier transform on R",
         "undergrad", ["Fourier transform","inverse transform","convolution theorem",
          "Plancherel theorem","Fourier transform on L1","Riemann-Lebesgue lemma"],
         ["analysis_fourier_series_intro"], 5, 10, 90),
        ("analysis_fourier_transform_L2", "Fourier变换在L^2上", "Fourier transform on L2",
         "undergrad", ["Fourier transform L2","Plancherel isometry","unitarity",
          "approximate identity in L2","density of Schwartz","completeness"],
         ["analysis_fourier_transform_real"], 5, 9, 90),
        ("analysis_poisson_summation", "Poisson求和公式", "Poisson summation formula",
         "undergrad", ["Poisson summation","theta function","Poisson summation formula",
          "Fourier series of lattice Dirac comb","sampling theorem",
          "Nyquist-Shannon"],
         ["analysis_fourier_transform_real"], 5, 9, 90),
        ("analysis_distributions", "广义函数/分布", "distributions",
         "undergrad", ["distribution","generalized function","Dirac delta",
          "tempered distribution","Schwartz space","test function",
          "derivative of distributions","distribution topology"],
         ["analysis_fourier_transform_L2"], 6, 9, 120),
        ("analysis_heisenberg_uncertainty", "Heisenberg不确定性原理", "Heisenberg uncertainty principle",
         "undergrad", ["Heisenberg uncertainty","uncertainty principle Fourier",
          "time-frequency","Fourier transform inequality",
          "Paley-Wiener","hardy theorem"],
         ["analysis_distributions"], 5, 9, 90),

        # 泛函分析
        ("analysis_banach_space_intro", "Banach空间", "Banach spaces",
         "undergrad", ["Banach space","complete normed vector space","norm completeness",
          "all Lp are Banach","Banach-Steinhaus","closed graph"],
         ["analysis_lp_spaces"], 5, 9, 90),
        ("analysis_hilbert_space_intro", "Hilbert空间", "Hilbert spaces",
         "undergrad", ["Hilbert space","complete inner product space","orthogonality",
          "parallelogram law","projection theorem","Riesz representation"],
         ["analysis_l2_hilbert"], 5, 10, 90),
        ("analysis_riesz_representation_hilbert", "Riesz表示定理（Hilbert）", "Riesz representation theorem Hilbert",
         "undergrad", ["Riesz representation theorem","every bounded linear functional inner product",
          "Riesz lemma","anti-dual","conjugate linear functional"],
         ["analysis_hilbert_space_intro"], 5, 10, 60),
        ("analysis_orthonormal_basis_hilbert", "正交规范基", "orthonormal bases in Hilbert space",
         "undergrad", ["orthonormal basis","complete orthonormal system",
          "Fourier series general Hilbert","Parseval identity Hilbert",
          "separable Hilbert","Gram-Schmidt"],
         ["analysis_hilbert_space_intro"], 4, 9, 60),
        ("analysis_bessel_inequality", "Bessel不等式", "Bessel inequality",
         "undergrad", ["Bessel inequality","orthonormal system","energy inequality",
          "Parseval iff complete","Fourier series Hilbert"],
         ["analysis_orthonormal_basis_hilbert"], 4, 8, 45),
        ("analysis_riesz_lemma", "Riesz引理", "Riesz lemma",
         "undergrad", ["Riesz lemma","almost orthogonal element","infinite-dimensional normed space",
          "almost perpendicular","constructing sequences"],
         ["analysis_banach_space_intro"], 5, 8, 45),
        ("analysis_projection_theorem", "投影定理", "projection theorem",
         "undergrad", ["projection theorem","closed convex subset Hilbert",
          "unique closest point","orthogonal projection","best approximation"],
         ["analysis_hilbert_space_intro"], 5, 9, 60),
        ("analysis_dual_space_banach", "Banach空间的对偶", "dual spaces of Banach spaces",
         "undergrad", ["dual space","Banach dual","continuous linear functional",
          "bidual","reflexive"," Hahn-Banach","double dual"],
         ["analysis_banach_space_intro"], 5, 9, 60),
        ("analysis_hahn_banach", "Hahn-Banach定理", "Hahn-Banach theorem",
         "undergrad", ["Hahn-Banach theorem","extension of linear functional",
          "dominated linear functional","sublinear functional","separation theorems",
          "geometric Hahn-Banach","norm preserving"],
         ["analysis_dual_space_banach"], 6, 10, 90),
        ("analysis_separation_convex", "分离定理", "separation theorems",
         "undergrad", ["separation theorem","hyperplane separation","strictly separated",
          "convex sets","supporting hyperplane","Farkas lemma"],
         ["analysis_hahn_banach"], 5, 9, 60),
        ("analysis_banach_steinhaus", "Banach-Steinhaus定理", "Banach-Steinhaus theorem",
         "undergrad", ["Banach-Steinhaus","uniform boundedness principle",
          "equicontinuous implies bounded","pointwise bounded implies uniform bounded",
          "barrelled space","TP theorem"],
         ["analysis_banach_space_intro"], 6, 10, 90),
        ("analysis_open_mapping_theorem_functional", "开映射定理（泛函）", "open mapping theorem functional analysis",
         "undergrad", ["open mapping theorem","continuous surjective Banach",
          "open image of open set","bounded inverse theorem",
          "closed graph theorem","closed graph"],
         ["analysis_banach_space_intro"], 6, 10, 60),
        ("analysis_closed_graph_theorem", "闭图像定理", "closed graph theorem",
         "undergrad", ["closed graph theorem","bounded linear operator",
          "closed graph implies bounded","mutual continuity","Banach spaces"],
         ["analysis_open_mapping_theorem_functional"], 5, 9, 60),
        ("analysis_uniform_boundedness", "一致有界原理", "uniform boundedness principle",
         "undergrad", ["uniform boundedness principle","Banach-Steinhaus",
          "family of operators pointwise bounded","implies uniform bound",
          "barrelled spaces","resonance theorem"],
         ["analysis_banach_steinhaus"], 5, 9, 60),
        ("analysis_spectrum_operator", "算子谱", "spectrum of an operator",
         "undergrad", ["spectrum","resolvent","resolvent set","spectral radius",
          "point spectrum","continuous spectrum","residual spectrum",
          "compact operator spectrum","self-adjoint spectrum"],
         ["analysis_hilbert_space_intro"], 5, 9, 90),
        ("analysis_compact_operator", "紧算子", "compact operators",
         "undergrad", ["compact operator","completely continuous","bounded image relatively compact",
          "approximation property","spectrum of compact","Fredholm alternative",
          "Riesz-Schauder theory","index"],
         ["analysis_spectrum_operator"], 6, 9, 120),
        ("analysis_schauder_fixed_point", "Schauder不动点定理", "Schauder fixed point theorem",
         "undergrad", ["Schauder fixed point theorem","compact convex set",
          "continuous map fixed point","Brouwer fixed point","Schauder-Tychonoff"],
         ["analysis_compact_operator"], 6, 9, 60),
        ("analysis_krein_smulian", "Krein-Smulian定理", "Krein-Smulian theorem",
         "undergrad", ["Krein-Smulian theorem","weak* compactness",
          "convex hull closed","barrelled","Banach Alaoglu","boundedness"],
         ["analysis_banach_space_intro"], 6, 8, 60),
        ("analysis_krein_rukhin", "Krein-Rukhlin定理", "Krein-Ruthlin theorem",
         "undergrad", ["Krein-Ruthlin theorem","eigenvalue distribution",
          "random matrices connection","asymptotic distribution","TOE","unitary invariant"],
         ["analysis_spectrum_operator"], 6, 8, 90),
        ("analysis_sobolev_spaces", "Sobolev空间", "Sobolev spaces",
         "undergrad", ["Sobolev space","W^{k,p}","weak derivative","distributional derivative",
          "Sobolev embedding theorem","Rellich-Kondrachov","trace theorem",
          "Sobolev inequality","Poincare inequality"],
         ["analysis_lp_spaces"], 6, 10, 120),

        # 高级专题
        ("analysis_ascoli_arzela", "Arzela-Ascoli定理", "Arzela-Ascoli theorem",
         "undergrad", ["Arzela-Ascoli theorem","equicontinuous","pointwise bounded implies subsequence",
          "normal families complex","uniform boundedness continuous",
          "compactness in C(K)","Urysohn"],
         ["analysis_uniform_boundedness"], 5, 9, 60),
        ("analysis_spectrum_self_adjoint", "自伴算子谱定理", "spectral theorem for self-adjoint operators",
         "master", ["spectral theorem self-adjoint","continuous functional calculus",
          "Borel functional calculus","multiplication operator","diagonalization",
          "unitary equivalence","real spectral theorem"],
         ["analysis_spectrum_operator"], 6, 10, 120),
        ("analysis_spectrum_unbounded", "无界算子谱定理", "spectral theorem for unbounded operators",
         "master", ["spectral theorem unbounded","self-adjoint operators",
          "Stone theorem","one-parameter unitary group","functional calculus unbounded",
          "resolution of identity","Cayley transform"],
         ["analysis_spectrum_self_adjoint"], 7, 10, 120),
        ("analysis_stone_theorem", "Stone定理", "Stone theorem on one-parameter unitary groups",
         "master", ["Stone theorem","one-parameter unitary group","infinitesimal generator",
          "self-adjoint generator","Hille-Yosida","unitary representation","turbulence"],
         ["analysis_spectrum_unbounded"], 7, 10, 120),
        ("analysis_calkin_algebra", "Calkin代数", "Calkin algebra",
         "master", ["Calkin algebra","B(H)/K(H)","Fredholm operators","Fredholm index",
          "Atkinson theorem","essential spectrum","semi-Fredholm"],
         ["analysis_compact_operator"], 7, 9, 120),
        ("analysis_fredholm_alternative", "Fredholm选择定理", "Fredholm alternative",
         "master", ["Fredholm alternative","solvability conditions",
          "compact perturbation","adjoint Fredholm