#!/usr/bin/env python3
"""扩展数学知识图谱数据"""

import json

def create_node(node_id, name_zh, name_en, desc_zh, desc_en, node_type, level, branch, tags, prerequisites, difficulty, importance, minutes):
    return {
        "id": node_id,
        "type": node_type,
        "name": {"zh": name_zh, "en": name_en},
        "description": {"zh": desc_zh, "en": desc_en},
        "level": level,
        "branch": branch,
        "tags": tags,
        "prerequisites": prerequisites,
        "difficulty": difficulty,
        "importance": importance,
        "estimated_minutes": minutes
    }

nodes = []

# 小学
nodes.extend([
    create_node("natural_numbers", "自然数", "Natural Numbers", "计数", "Counting", "concept", "primary", "arithmetic", ["基础"], [], 1, 10, 30),
    create_node("zero", "零", "Zero", "无", "Nothing", "concept", "primary", "arithmetic", ["基础"], ["natural_numbers"], 1, 10, 20),
    create_node("whole_numbers", "整数", "Whole Numbers", "自然数和零", "Nat+zero", "concept", "primary", "arithmetic", ["数系"], ["zero"], 1, 9, 30),
    create_node("addition", "加法", "Addition", "合并", "Combine", "concept", "primary", "arithmetic", ["运算"], ["natural_numbers"], 1, 10, 45),
    create_node("subtraction", "减法", "Subtraction", "去掉", "Remove", "concept", "primary", "arithmetic", ["运算"], ["addition"], 2, 10, 60),
    create_node("multiplication", "乘法", "Multiplication", "重复加", "Repeated add", "concept", "primary", "arithmetic", ["运算"], ["addition"], 2, 10, 90),
    create_node("division", "除法", "Division", "均分", "Equal split", "concept", "primary", "arithmetic", ["运算"], ["multiplication"], 3, 10, 120),
    create_node("fractions", "分数", "Fractions", "部分", "Parts", "concept", "primary", "arithmetic", ["数系"], ["division"], 3, 10, 180),
    create_node("decimals", "小数", "Decimals", "十进", "Decimal", "concept", "primary", "arithmetic", ["数系"], ["fractions"], 3, 9, 150),
    create_node("percentage", "百分数", "Percentages", "百分", "Percent", "concept", "primary", "arithmetic", ["数系"], ["fractions"], 3, 9, 120),
    create_node("basic_geometry", "基础几何", "Basic Geometry", "点线面", "Points lines planes", "concept", "primary", "geometry", ["基础"], [], 1, 10, 60),
    create_node("lines_angles", "直线角", "Lines Angles", "线角", "Lines angles", "concept", "primary", "geometry", ["基础"], ["basic_geometry"], 2, 9, 90),
    create_node("triangles", "三角形", "Triangles", "三边", "Three sides", "concept", "primary", "geometry", ["图形"], ["lines_angles"], 2, 10, 180),
    create_node("quadrilaterals", "四边形", "Quadrilaterals", "四边", "Four sides", "concept", "primary", "geometry", ["图形"], ["triangles"], 2, 9, 120),
    create_node("circles", "圆", "Circles", "圆形", "Round", "concept", "primary", "geometry", ["图形"], ["basic_geometry"], 2, 9, 120),
    create_node("area_perimeter", "面积周长", "Area Perimeter", "大小", "Size", "concept", "primary", "geometry", ["计算"], ["triangles", "circles"], 2, 10, 180),
])

# 初中
nodes.extend([
    create_node("negative_numbers", "负数", "Negative Numbers", "小于零", "Less than zero", "concept", "junior", "arithmetic", ["数系"], ["whole_numbers"], 2, 9, 60),
    create_node("integers", "整数", "Integers", "正负零", "Pos neg zero", "concept", "junior", "arithmetic", ["数系"], ["negative_numbers"], 2, 9, 45),
    create_node("rational_numbers", "有理数", "Rational Numbers", "可比", "Ratio", "concept", "junior", "arithmetic", ["数系"], ["fractions", "integers"], 2, 9, 60),
    create_node("irrational_numbers", "无理数", "Irrational Numbers", "不可比", "Non-ratio", "concept", "junior", "arithmetic", ["数系"], ["rational_numbers"], 3, 8, 60),
    create_node("real_numbers", "实数", "Real Numbers", "有理+无理", "Rational+irrational", "concept", "junior", "arithmetic", ["数系"], ["irrational_numbers"], 3, 10, 60),
    create_node("square_root", "平方根", "Square Root", "逆运算", "Inverse", "concept", "junior", "arithmetic", ["运算"], ["multiplication"], 3, 9, 120),
    create_node("absolute_value", "绝对值", "Absolute Value", "大小", "Magnitude", "concept", "junior", "arithmetic", ["概念"], ["integers"], 2, 9, 60),
    create_node("variable", "变量", "Variable", "未知", "Unknown", "concept", "junior", "algebra", ["基础"], ["real_numbers"], 2, 10, 60),
    create_node("expression", "代数式", "Algebraic Expression", "式子", "Expression", "concept", "junior", "algebra", ["基础"], ["variable"], 2, 9, 90),
    create_node("equation", "方程", "Equation", "等式", "Equality", "concept", "junior", "algebra", ["基础"], ["expression"], 2, 10, 120),
    create_node("linear_one", "一元一次", "Linear 1 var", "一次方程", "First degree", "concept", "junior", "algebra", ["方程"], ["equation"], 2, 10, 120),
    create_node("linear_two", "二元一次", "Linear 2 vars", "两未知", "Two unknowns", "concept", "junior", "algebra", ["方程"], ["linear_one"], 3, 10, 180),
    create_node("linear_system", "方程组", "System", "组", "System", "concept", "junior", "algebra", ["方程"], ["linear_two"], 3, 10, 180),
    create_node("quadratic_eq", "一元二次", "Quadratic", "二次方程", "Second degree", "concept", "junior", "algebra", ["方程"], ["linear_one", "square_root"], 4, 10, 240),
    create_node("inequality", "不等式", "Inequality", "不等", "Inequality", "concept", "junior", "algebra", ["基础"], ["equation"], 3, 9, 120),
    create_node("polynomial", "多项式", "Polynomial", "多项", "Polynomial", "concept", "junior", "algebra", ["代数"], ["expression"], 3, 9, 180),
    create_node("factoring", "因式分解", "Factoring", "分解", "Factor", "concept", "junior", "algebra", ["运算"], ["polynomial"], 4, 10, 240),
    create_node("right_triangle", "直角三角形", "Right Triangle", "90度", "90 degree", "concept", "junior", "geometry", ["三角形"], ["triangles"], 2, 9, 90),
    create_node("congruent", "全等", "Congruence", "重合", "Coincide", "concept", "junior", "geometry", ["三角形"], ["triangles"], 3, 9, 120),
    create_node("similar", "相似", "Similarity", "对应", "Proportional", "concept", "junior", "geometry", ["三角形"], ["triangles"], 3, 9, 180),
    create_node("pythagorean", "勾股定理", "Pythagorean", "a2+b2=c2", "a2+b2=c2", "theorem", "junior", "geometry", ["定理"], ["right_triangle", "square_root"], 3, 10, 120),
    create_node("trig_ratio", "锐角三角比", "Trig Ratios", "边比", "Side ratios", "concept", "junior", "trigonometry", ["三角"], ["right_triangle"], 3, 10, 180),
    create_node("sine_cosine_tan", "正弦余弦正切", "Sine Cosine Tangent", "三角函数", "Trig functions", "concept", "junior", "trigonometry", ["三角函数"], ["trig_ratio"], 3, 10, 180),
    create_node("quad_props", "四边形性质", "Quad Properties", "性质", "Properties", "concept", "junior", "geometry", ["四边形"], ["quadrilaterals"], 3, 9, 180),
    create_node("circle_theorems", "圆定理", "Circle Theorems", "圆性质", "Circle props", "concept", "junior", "geometry", ["圆"], ["circles"], 4, 9, 240),
    create_node("data_collection", "数据收集", "Data Collection", "收集", "Collect", "concept", "junior", "statistics", ["统计"], [], 2, 8, 60),
    create_node("mean_median_mode", "平均中位数众数", "Central Tendency", "集中", "Central", "concept", "junior", "statistics", ["统计"], ["data_collection"], 2, 9, 90),
    create_node("range", "极差", "Range", "离散", "Dispersion", "concept", "junior", "statistics", ["统计量"], ["mean_median_mode"], 2, 8, 60),
    create_node("probability_junior", "概率基础", "Probability", "可能性", "Likelihood", "concept", "junior", "probability", ["基础"], ["fractions"], 3, 9, 120),
    create_node("set_theory", "集合", "Set Theory", "集合", "Set", "concept", "junior", "discrete", ["基础"], [], 2, 9, 120),
    create_node("counting_principle", "计数原理", "Counting", "原理", "Principles", "concept", "junior", "discrete", ["基础"], ["multiplication"], 3, 9, 120),
    create_node("permutation", "排列", "Permutation", "有序", "Ordered", "concept", "junior", "discrete", ["计数"], ["counting_principle"], 4, 9, 180),
    create_node("combination", "组合", "Combination", "无序", "Unordered", "concept", "junior", "discrete", ["计数"], ["permutation"], 4, 9, 180),
])

# 高中
nodes.extend([
    create_node("function", "函数", "Function", "对应", "Correspondence", "concept", "senior", "algebra", ["重要"], ["variable", "set_theory"], 3, 10, 120),
    create_node("linear_func", "一次函数", "Linear", "y=mx+b", "y=mx+b", "concept", "senior", "algebra", ["函数"], ["function"], 3, 10, 120),
    create_node("quadratic_func", "二次函数", "Quadratic", "y=ax2+bx+c", "y=ax2+bx+c", "concept", "senior", "algebra", ["函数"], ["function", "quadratic_eq"], 4, 10, 240),
    create_node("exponential", "指数函数", "Exponential", "y=ax", "y=ax", "concept", "senior", "algebra", ["函数"], ["function"], 4, 9, 180),
    create_node("logarithm", "对数", "Logarithm", "对数", "Logarithm", "concept", "senior", "algebra", ["运算"], ["exponential"], 4, 9, 180),
    create_node("logarithmic_func", "对数函数", "Logarithmic", "反函数", "Inverse", "concept", "senior", "algebra", ["函数"], ["logarithm"], 4, 9, 180),
    create_node("power_func", "幂函数", "Power Function", "y=x^n", "y=x^n", "concept", "senior", "algebra", ["函数"], ["function"], 4, 8, 120),
    create_node("inverse_func", "反函数", "Inverse Function", "逆", "Inverse", "concept", "senior", "algebra", ["函数"], ["function"], 4, 9, 120),
    create_node("composite_func", "复合函数", "Composite", "组合", "Composition", "concept", "senior", "algebra", ["函数"], ["function"], 4, 9, 180),
    create_node("unit_circle", "单位圆", "Unit Circle", "半径1", "Radius 1", "concept", "senior", "trigonometry", ["三角"], ["sine_cosine_tan", "circles"], 3, 10, 120),
    create_node("trig_functions", "三角函数", "Trig Functions", "任意角", "Any angle", "concept", "senior", "trigonometry", ["重要"], ["unit_circle"], 4, 10, 300),
    create_node("inverse_trig", "反三角", "Inverse Trig", "逆", "Inverse", "concept", "senior", "trigonometry", ["函数"], ["trig_functions", "inverse_func"], 5, 9, 180),
    create_node("trig_identities", "三角恒等式", "Trig Identities", "恒等", "Identities", "theorem", "senior", "trigonometry", ["重要"], ["trig_functions"], 4, 10, 240),
    create_node("trig_equations", "三角方程", "Trig Equations", "三角等式", "Trig eq", "concept", "senior", "trigonometry", ["方程"], ["trig_identities"], 5, 9, 240),
    create_node("limit", "极限", "Limit", "趋近", "Approach", "concept", "senior", "analysis", ["重要"], ["function", "real_numbers"], 4, 10, 240),
    create_node("continuity", "连续性", "Continuity", "连续", "Continuous", "concept", "senior", "analysis", ["分析"], ["limit"], 4, 9, 180),
    create_node("derivative", "导数", "Derivative", "变化率", "Rate change", "concept", "senior", "analysis", ["重要"], ["continuity"], 5, 10, 300),
    create_node("diff_rules", "求导法则", "Diff Rules", "公式", "Rules", "concept", "senior", "analysis", ["计算"], ["derivative"], 4, 10, 240),
    create_node("diff_applications", "导数应用", "Diff Applications", "极值", "Extremum", "concept", "senior", "analysis", ["应用"], ["diff_rules"], 5, 10, 300),
    create_node("integration", "积分", "Integration", "累积", "Accumulate", "concept", "senior", "analysis", ["重要"], ["derivative", "area_perimeter"], 5, 10, 360),
    create_node("integration_techniques", "积分技巧", "Integration Tech", "方法", "Methods", "concept", "senior", "analysis", ["计算"], ["integration"], 5, 9, 360),
    create_node("definite_integral", "定积分", "Definite Integral", "有限", "Finite", "concept", "senior", "analysis", ["计算"], ["integration"], 5, 10, 240),
    create_node("fundamental_theorem", "微积分基本定理", "Fund Theorem", "互逆", "Inverse", "theorem", "senior", "analysis", ["重要"], ["derivative", "definite_integral"], 5, 10, 240),
    create_node("integration_applications", "积分应用", "Int Applications", "应用", "Applications", "concept", "senior", "analysis", ["应用"], ["definite_integral"], 5, 10, 360),
    create_node("cartesian", "直角坐标系", "Cartesian", "坐标", "Coords", "concept", "senior", "geometry", ["基础"], [], 3, 10, 120),
    create_node("line_equation", "直线方程", "Line Eq", "直线", "Line", "concept", "senior", "geometry", ["方程"], ["cartesian", "linear_func"], 3, 9, 120),
    create_node("circle_eq", "圆方程", "Circle Eq", "圆", "Circle", "concept", "senior", "geometry", ["方程"], ["cartesian", "circles"], 3, 9, 120),
    create_node("ellipse", "椭圆", "Ellipse", "椭圆", "Ellipse", "concept", "senior", "geometry", ["曲线"], ["circle_eq"], 4, 9, 240),
    create_node("hyperbola", "双曲线", "Hyperbola", "双曲线", "Hyperbola", "concept", "senior", "geometry", ["曲线"], ["ellipse"], 4, 9, 240),
    create_node("parabola", "抛物线", "Parabola", "抛物线", "Parabola", "concept", "senior", "geometry", ["曲线"], ["quadratic_func"], 4, 9, 240),
    create_node("conic_sections", "圆锥曲线", "Conic Sections", "圆锥截线", "Conics", "concept", "senior", "geometry", ["重要"], ["circle_eq", "ellipse", "hyperbola", "parabola"], 4, 10, 180),
    create_node("spatial_geometry", "空间几何", "Spatial Geometry", "3D", "3D", "concept", "senior", "geometry", ["几何"], [], 4, 9, 180),
    create_node("plane_in_space", "空间平面", "Planes", "平面", "Planes", "concept", "senior", "geometry", ["基础"], ["spatial_geometry"], 4, 9, 120),
    create_node("line_in_space", "空间直线", "Lines", "直线", "Lines", "concept", "senior", "geometry", ["基础"], ["plane_in_space"], 4, 8, 120),
    create_node("perpendicular_space", "垂直", "Perpendicular", "垂直", "Perp", "concept", "senior", "geometry", ["关系"], ["line_in_space", "plane_in_space"], 5, 9, 180),
    create_node("parallel_space", "平行", "Parallel", "平行", "Parallel", "concept", "senior", "geometry", ["关系"], ["perpendicular_space"], 5, 9, 180),
    create_node("dihedral_angle", "二面角", "Dihedral Angle", "面角", "Face angle", "concept", "senior", "geometry", ["角"], ["perpendicular_space"], 5, 8, 120),
    create_node("polyhedron", "多面体", "Polyhedron", "多面", "Many faces", "concept", "senior", "geometry", ["立体"], ["spatial_geometry"], 4, 9, 180),
    create_node("prism", "棱柱", "Prism", "棱柱", "Prism", "concept", "senior", "geometry", ["立体"], ["polyhedron"], 4, 8, 120),
    create_node("pyramid", "棱锥", "Pyramid", "棱锥", "Pyramid", "concept", "senior", "geometry", ["立体"], ["polyhedron"], 4, 8, 120),
    create_node("sphere_3d", "球体", "Sphere", "球", "Sphere", "concept", "senior", "geometry", ["立体"], ["spatial_geometry"], 4, 9, 180),
    create_node("spatial_vector", "空间向量", "Spatial Vectors", "3D向量", "3D vectors", "concept", "senior", "geometry", ["向量"], ["spatial_geometry"], 5, 9, 240),
    create_node("sequence", "数列", "Sequence", "数列", "Sequence", "concept", "senior", "algebra", ["重要"], ["function"], 3, 9, 120),
    create_node("arithmetic_progression", "等差数列", "Arithmetic", "等差", "Const diff", "concept", "senior", "algebra", ["数列"], ["sequence"], 3, 9, 120),
    create_node("geometric_progression", "等比数列", "Geometric", "等比", "Const ratio", "concept", "senior", "algebra", ["数列"], ["sequence"], 3, 9, 120),
    create_node("sequence_limit", "数列极限", "Seq Limit", "极限", "Limit", "concept", "senior", "algebra", ["极限"], ["arithmetic_progression", "geometric_progression", "limit"], 4, 9, 180),
    create_node("math_induction", "数学归纳法", "Induction", "归纳", "Induction", "concept", "senior", "algebra", ["方法"], ["arithmetic_progression"], 4, 9, 180),
    create_node("binomial_theorem", "二项式定理", "Binomial", "二项", "Binomial", "theorem", "senior", "algebra", ["定理"], ["combination", "math_induction"], 4, 9, 180),
    create_node("complex_numbers", "复数", "Complex Numbers", "a+bi", "a+bi", "concept", "senior", "arithmetic", ["数系"], ["real_numbers", "quadratic_eq"], 4, 9, 180),
    create_node("probability_theory", "概率论", "Probability Theory", "概率", "Probability", "concept", "senior", "probability", ["重要"], ["probability_junior", "set_theory"], 4, 10, 300),
    create_node("random_variable", "随机变量", "Random Variable", "随机", "Random", "concept", "senior", "probability", ["重要"], ["probability_theory"], 4, 10, 240),
    create_node("expectation", "数学期望", "Expectation", "期望", "Expected", "concept", "senior", "probability", ["统计量"], ["random_variable"], 4, 9, 180),
    create_node("variance", "方差", "Variance", "离散", "Dispersion", "concept", "senior", "probability", ["统计量"], ["expectation"], 4, 9, 180),
    create_node("distribution", "概率分布", "Distribution", "分布", "Distribution", "concept", "senior", "probability", ["重要"], ["random_variable"], 5, 10, 240),
    create_node("binomial_distribution", "二项分布", "Binomial", "二项", "Binomial", "concept", "senior", "probability", ["分布"], ["distribution", "combination"], 5, 9, 180),
    create_node("normal_distribution", "正态分布", "Normal", "正态", "Normal", "concept", "senior", "probability", ["重要"], ["distribution"], 5, 10, 180),
])

# 本科
nodes.extend([
    create_node("matrix", "矩阵", "Matrix", "数表", "Array", "concept", "undergrad", "algebra", ["重要"], ["linear_system"], 4, 10, 240),
    create_node("matrix_operations", "矩阵运算", "Matrix Ops", "运算", "Operations", "concept", "undergrad", "algebra", ["计算"], ["matrix"], 4, 9, 180),
    create_node("determinant", "行列式", "Determinant", "行列式", "Determinant", "concept", "undergrad", "algebra", ["重要"], ["matrix"], 4, 10, 240),
    create_node("matrix_rank", "矩阵秩", "Rank", "秩", "Rank", "concept", "undergrad", "algebra", ["概念"], ["determinant"], 5, 9, 120),
    create_node("linear_transformation", "线性变换", "Linear Transform", "线性映射", "Linear map", "concept", "undergrad", "algebra", ["重要"], ["matrix", "vector_space"], 5, 10, 240),
    create_node("eigenvalue", "特征值", "Eigenvalue", "特征值", "Eigenvalue", "concept", "undergrad", "algebra", ["重要"], ["linear_transformation"], 6, 10, 300),
    create_node("eigenvector", "特征向量", "Eigenvector", "特征向量", "Eigenvector", "concept", "undergrad", "algebra", ["重要"], ["eigenvalue"], 6, 10, 240),
    create_node("jordan_form", "Jordan形", "Jordan Form", "Jordan", "Jordan", "concept", "undergrad", "algebra", ["进阶"], ["eigenvalue"], 7, 8, 300),
    create_node("vector_space", "向量空间", "Vector Space", "向量空间", "Vector space", "concept", "undergrad", "algebra", ["重要"], ["spatial_vector"], 5, 10, 240),
    create_node("linear_independence", "线性无关", "Linear Independence", "线性无关", "Independent", "concept", "undergrad", "algebra", ["基础"], ["vector_space"], 5, 10, 180),
    create_node("basis_dimension", "基与维数", "Basis Dimension", "基维", "Basis dim", "concept", "undergrad", "algebra", ["重要"], ["linear_independence"], 5, 10, 180),
    create_node("inner_product", "内积", "Inner Product", "内积", "Inner prod", "concept", "undergrad", "algebra", ["重要"], ["vector_space"], 5, 9, 180),
    create_node("orthogonal", "正交", "Orthogonal", "正交", "Orthogonal", "concept", "undergrad", "algebra", ["重要"], ["inner_product"], 5, 9, 180),
    create_node("quadratic_form", "二次型", "Quadratic Form", "二次型", "Quadratic", "concept", "undergrad", "algebra", ["重要"], ["polynomial", "matrix"], 6, 9, 240),
    create_node("group_theory", "群论", "Group Theory", "群", "Group", "concept", "undergrad", "algebra", ["重要"], ["set_theory"], 5, 10, 300),
    create_node("subgroup", "子群", "Subgroup", "子群", "Subgroup", "concept", "undergrad", "algebra", ["基础"], ["group_theory"], 5, 9, 180),
    create_node("coset", "陪集", "Coset", "陪集", "Coset", "concept", "undergrad", "algebra", ["概念"], ["subgroup"], 6, 8, 120),
    create_node("normal_subgroup", "正规子群", "Normal Subgroup", "正规", "Normal", "concept", "undergrad", "algebra", ["概念"], ["coset"], 6, 9, 120),
    create_node("homomorphism", "同态", "Homomorphism", "映射", "Map", "concept", "undergrad", "algebra", ["重要"], ["group_theory"], 6, 9, 180),
    create_node("isomorphism", "同构", "Isomorphism", "同构", "Iso", "concept", "undergrad", "algebra", ["重要"], ["homomorphism"], 6, 10, 180),
    create_node("quotient_group", "商群", "Quotient Group", "商", "Quotient", "concept", "undergrad", "algebra", ["进阶"], ["normal_subgroup"], 6, 9, 120),
    create_node("ring_theory", "环论", "Ring Theory", "环", "Ring", "concept", "undergrad", "algebra", ["重要"], ["group_theory"], 6, 9, 240),
    create_node("field_theory", "域论", "Field Theory", "域", "Field", "concept", "undergrad", "algebra", ["重要"], ["ring_theory"], 6, 10, 300),
    create_node("galois_theory", "伽罗瓦理论", "Galois Theory", "伽罗瓦", "Galois", "theory", "undergrad", "algebra", ["高级"], ["field_theory"], 8, 10, 360),
    create_node("real_analysis", "实分析", "Real Analysis", "实分析", "Real analysis", "concept", "undergrad", "analysis", ["重要"], ["real_numbers", "limit"], 5, 10, 360),
    create_node("sequence_limit_undergrad", "数列极限", "Seq Limit", "极限", "Limit", "concept", "undergrad", "analysis", ["基础"], ["real_analysis"], 5, 10, 240),
    create_node("series", "级数", "Series", "级数", "Series", "concept", "undergrad", "analysis", ["重要"], ["sequence_limit_undergrad"], 5, 10, 300),
    create_node("convergence_tests", "收敛判别", "Convergence Tests", "判别", "Tests", "concept", "undergrad", "analysis", ["计算"], ["series"], 5, 9, 240),
    create_node("power_series", "幂级数", "Power Series", "幂级数", "Power series", "concept", "undergrad", "analysis", ["重要"], ["series"], 6, 9, 240),
    create_node("taylor_series", "泰勒级数", "Taylor Series", "泰勒", "Taylor", "concept", "undergrad", "analysis", ["重要"], ["power_series", "derivative"], 6, 10, 300),
    create_node("multivariable_calculus", "多元微积分", "Multivariable", "多变量", "Multiple var", "concept", "undergrad", "analysis", ["重要"], ["derivative", "integration"], 6, 10, 360),
    create_node("partial_derivative", "偏导数", "Partial Deriv", "偏导", "Partial", "concept", "undergrad", "analysis", ["重要"], ["multivariable_calculus"], 6, 10, 240),
    create_node("multiple_integral", "多重积分", "Multiple Integral", "多重积分", "Multiple int", "concept", "undergrad", "analysis", ["重要"], ["partial_derivative", "integration"], 6, 10, 300),
    create_node("line_integral", "曲线积分", "Line Integral", "曲线积分", "Line int", "concept", "undergrad", "analysis", ["计算"], ["multiple_integral"], 7, 9, 240),
    create_node("surface_integral", "曲面积分", "Surface Integral", "面积分", "Surface int", "concept", "undergrad", "analysis", ["计算"], ["line_integral"], 7, 9, 240),
    create_node("divergence_theorem", "散度定理", "Divergence Theorem", "散度", "Divergence", "theorem", "undergrad", "analysis", ["重要"], ["surface_integral"], 7, 9, 180),
    create_node("stokes_theorem", "Stokes定理", "Stokes Theorem", "旋度", "Curl", "theorem", "undergrad", "analysis", ["重要"], ["surface_integral"], 7, 9, 180),
    create_node("complex_analysis", "复分析", "Complex Analysis", "复分析", "Complex", "concept", "undergrad", "analysis", ["重要"], ["complex_numbers", "real_analysis"], 6, 10, 360),
    create_node("analytic_function", "解析函数", "Analytic Function", "全纯", "Holomorphic", "concept", "undergrad", "analysis", ["重要"], ["complex_analysis"], 6, 10, 240),
    create_node("cauchy_theorem", "柯西定理", "Cauchy Theorem", "柯西", "Cauchy", "theorem", "undergrad", "analysis", ["重要"], ["analytic_function"], 6, 10, 180),
    create_node("cauchy_formula", "柯西公式", "Cauchy Formula", "公式", "Formula", "formula", "undergrad", "analysis", ["重要"], ["cauchy_theorem"], 6, 10, 180),
    create_node("residue_theorem", "留数定理", "Residue Theorem", "留数", "Residue", "theorem", "undergrad", "analysis", ["重要"], ["cauchy_formula"], 7, 9, 180),
    create_node("differential_equations", "常微分方程", "ODE", "ODE", "ODE", "concept", "undergrad", "analysis", ["重要"], ["derivative", "integration"], 5, 10, 300),
    create_node("first_order_ode", "一阶ODE", "First Order ODE", "一阶", "First order", "concept", "undergrad", "analysis", ["基础"], ["differential_equations"], 5, 9, 180),
    create_node("second_order_ode", "二阶ODE", "Second Order ODE", "二阶", "Second order", "concept", "undergrad", "analysis", ["重要"], ["first_order_ode"], 6, 10, 240),
    create_node("linear_ode", "线性ODE", "Linear ODE", "线性", "Linear", "concept", "undergrad", "analysis", ["重要"], ["second_order_ode", "matrix"], 6, 10, 240),
    create_node("laplace_transform", "拉普拉斯变换", "Laplace Transform", "拉普拉斯", "Laplace", "concept", "undergrad", "analysis", ["重要"], ["linear_ode", "integral_transform"], 7, 9, 240),
    create_node("integral_transform", "积分变换", "Integral Transform", "积分变换", "Integral transform", "concept", "undergrad", "analysis", ["方法"], ["integration"], 6, 8, 180),
])

# 硕士
nodes.extend([
    create_node("functional_analysis", "泛函分析", "Functional Analysis", "无限维", "Infinite dim", "concept", "master", "analysis", ["重要"], ["real_analysis", "vector_space"], 7, 10, 360),
    create_node("normed_space", "赋范空间", "Normed Space", "范数", "Norm", "concept", "master", "analysis", ["基础"], ["functional_analysis"], 7, 10, 240),
    create_node("banach_space", "Banach空间", "Banach Space", "完备", "Complete", "concept", "master", "analysis", ["重要"], ["normed_space"], 7, 10, 180),
    create_node("hilbert_space", "Hilbert空间", "Hil