#!/usr/bin/env python3
"""
给数学知识图谱节点添加具体年级标签
小学: 一年级~六年级
初中: 初一~初三
高中: 高一~高三
"""

import json

# 年级标签映射
PRIMARY_GRADE_TAGS = {
    1: "小学一年级",
    2: "小学二年级",
    3: "小学三年级",
    4: "小学四年级",
    5: "小学五年级",
    6: "小学六年级",
}

JUNIOR_GRADE_TAGS = {
    1: "初中一年级",
    2: "初中二年级",
    3: "初中三年级",
}

SENIOR_GRADE_TAGS = {
    1: "高中一年级",
    2: "高中二年级",
    3: "高中三年级",
}

# ============================================================
# 小学节点 → 年级映射
# 依据：中国小学数学课程标准
# ============================================================
PRIMARY_NODE_GRADES = {
    # 一年级：数数、加减法基础、认识图形
    "natural_numbers": 1,
    "natural_number": 1,
    "cardinal_number": 1,
    "ordinal_number": 1,
    "counting_unit": 1,
    "zero": 1,
    "addition": 1,
    "addition_meaning": 1,
    "addition_commutative": 1,
    "subtraction": 1,
    "subtraction_meaning": 1,
    "even_number": 1,
    "odd_number": 1,
    "point_line_plane": 1,
    "translation": 1,
    "rotation": 1,
    "cuboid": 1,
    "possibility": 1,
    "year_p": 1,
    "day_p": 1,
    "hour_p": 1,
    "minute_p": 1,
    "second_p": 1,
    "meter_p": 1,
    "centimeter": 1,
    "millimeter": 1,
    "kilogram_p": 1,
    "gram_p": 1,
    "rmb_yuan": 1,
    "rmb_jiao": 1,
    "rmb_fen": 1,
    "line_straight": 1,
    "line_ray": 1,
    "angle_p": 1,
    "angle_right_p": 1,
    "angle_acute_p": 1,
    "angle_obtuse_p": 1,
    "circle_center": 1,
    "circle_radius_p": 1,
    "circle_diameter_p": 1,

    # 二年级：乘除法、时间、长度
    "multiplication": 2,
    "multiplication_table": 2,
    "multiplication_meaning": 2,
    "multiplication_commutative": 2,
    "multiplication_associative": 2,
    "division": 2,
    "division_meaning": 2,
    "addition_associative": 2,
    "subtraction_borrow": 2,
    "whole_numbers": 2,
    "decimal_system": 2,
    "digit_place": 2,
    "line_segment": 2,
    "ray": 2,
    "line": 2,
    "angle": 2,
    "angle_measure": 2,
    "acute_angle": 2,
    "right_angle": 2,
    "obtuse_angle": 2,
    "month_p": 2,
    "leap_year": 2,
    "decimeter": 2,
    "century": 2,

    # 三年级：分数初步、面积、周长、统计
    "division_remainder": 3,
    "fractions": 3,
    "fraction_concept": 3,
    "fraction_unit": 3,
    "proper_fraction": 3,
    "improper_fraction": 3,
    "mixed_number": 3,
    "fraction_compare": 3,
    "triangle": 3,
    "triangle_classify": 3,
    "triangle_angle_sum": 3,
    "quadrilateral": 3,
    "rectangle": 3,
    "square": 3,
    "parallelogram": 3,
    "trapezoid": 3,
    "area": 3,
    "area_rectangle": 3,
    "area_square": 3,
    "area_triangle": 3,
    "perimeter": 3,
    "parallel": 3,
    "perpendicular": 3,
    "parallel_line_p": 3,
    "perpendicular_line_p": 3,
    "straight_angle": 3,
    "full_angle": 3,
    "triangle_p": 3,
    "triangle_by_angle_p": 3,
    "triangle_by_side_p": 3,
    "triangle_stability": 3,
    "quadrilateral_p": 3,
    "parallelogram_p": 3,
    "rectangle_p": 3,
    "square_p": 3,
    "trapezoid_p": 3,
    "data_organization": 3,
    "statistical_table": 3,
    "bar_chart": 3,
    "kilometer": 3,
    "square_meter_p": 3,

    # 四年级：小数、大数、角的度量、统计图
    "decimals": 4,
    "decimal_number": 4,
    "decimal_integer_part": 4,
    "decimal_fractional_part": 4,
    "decimal_basic_property": 4,
    "decimal_add_sub": 4,
    "decimal_multiply": 4,
    "decimal_divide": 4,
    "multiplication_distributive": 4,
    "symmetry": 4,
    "axial_symmetry": 4,
    "rotation_p": 4,
    "line_chart": 4,
    "pie_chart": 4,
    "average": 4,
    "square_kilometer": 4,
    "hectare": 4,
    "cubic_meter": 4,
    "liter": 4,
    "milliliter": 4,
    "ton": 4,

    # 五年级：因数倍数、分数运算、方程初步、体积
    "multiple": 5,
    "factor_divisor": 5,
    "divisible_by_2": 5,
    "divisible_by_5": 5,
    "divisible_by_3": 5,
    "prime_number": 5,
    "composite_number": 5,
    "common_factor": 5,
    "gcf": 5,
    "common_multiple": 5,
    "lcm": 5,
    "coprime": 5,
    "fraction_add": 5,
    "fraction_multiply": 5,
    "fraction_divide": 5,
    "fraction_basic_property": 5,
    "cube": 5,
    "cuboid_volume": 5,
    "cube_volume": 5,
    "cube_geo_p": 5,
    "cylinder_p": 5,
    "cone_p": 5,
    "volume_p": 5,
    "capacity": 5,
    "represent_number_with_letter": 5,
    "equation_concept": 5,
    "equation_property": 5,
    "circle": 5,
    "radius_diameter": 5,
    "circumference": 5,
    "circle_area": 5,
    "circle_p": 5,
    "circle_radius_diameter_relation": 5,

    # 六年级：比例、百分数、统计、综合应用
    "percentage": 6,
    "ratio": 6,
    "ratio_simplify": 6,
    "proportion": 6,
    "ratio_concept": 6,
    "ratio_value": 6,
    "ratio_basic_property": 6,
    "proportion_basic_property": 6,
    "direct_proportion": 6,
    "inverse_proportion": 6,
    "estimation": 6,
    "distance_speed_time": 6,
    "total_price_unit_price_quantity": 6,
    "work_total_efficiency_time": 6,
    "quotient_invariant": 6,
    "coordinate_pair": 6,
    "scale_p": 6,
    "addition_meaning": 1,  # 已在一年级，保持
}

# ============================================================
# 初中节点 → 年级映射
# 依据：中国初中数学课程标准
# ============================================================
JUNIOR_NODE_GRADES = {
    # 初一：有理数、整式、方程、几何基础
    "negative_numbers": 1,
    "integers": 1,
    "absolute_value": 1,
    "rational_numbers": 1,
    "positive_number": 1,
    "negative_number": 1,
    "rational_number": 1,
    "number_line": 1,
    "opposite_number": 1,
    "absolute_value_j": 1,
    "rational_comparison": 1,
    "rational_addition": 1,
    "rational_subtraction": 1,
    "rational_multiplication": 1,
    "rational_division": 1,
    "power_j": 1,
    "variable": 1,
    "expression": 1,
    "monomial": 1,
    "polynomial": 1,
    "like_terms": 1,
    "algebraic_expression": 1,
    "monomial_coefficient": 1,
    "monomial_degree": 1,
    "polynomial_term": 1,
    "combine_like_terms": 1,
    "equation": 1,
    "linear_one": 1,
    "linear_equation_one": 1,
    "euclidean_point": 1,
    "euclidean_line": 1,
    "euclidean_plane": 1,
    "angle_right": 1,
    "angle_acute": 1,
    "angle_obtuse": 1,
    "triangle_definition": 1,
    "triangle_by_sides": 1,
    "triangle_by_angles": 1,
    "solid_figure": 1,
    "plane_figure_j": 1,
    "point_line_plane_j": 1,
    "two_points_determine_line": 1,
    "shortest_line_segment": 1,
    "midpoint": 1,
    "angle_degree_minute_second": 1,
    "angle_bisector_j": 1,
    "complementary_angle": 1,
    "supplementary_angle": 1,
    "adjacent_supplementary": 1,
    "vertical_angles": 1,
    "perpendicular_j": 1,
    "variable_j2": 1,
    "constant_j2": 1,
    "variable_constant": 1,
    "impossible_event_j": 1,
    "random_event_j": 1,
    "data_collection": 1,
    "mean": 1,
    "median": 1,
    "mode": 1,
    "population": 1,
    "sample": 1,
    "median_j": 1,
    "mode_j": 1,

    # 初二：整式运算、因式分解、分式、平行线、三角形全等、勾股定理
    "power_operations": 2,
    "polynomial_multiplication": 2,
    "difference_of_squares": 2,
    "perfect_square": 2,
    "factoring": 2,
    "factorization": 2,
    "factor_common": 2,
    "factor_formula": 2,
    "cross_factorization": 2,
    "fractional_expression": 2,
    "fraction_reduction": 2,
    "fraction_addition": 2,
    "linear_two": 2,
    "linear_system": 2,
    "linear_equation_two": 2,
    "system_linear_eq": 2,
    "substitution_elimination": 2,
    "addition_elimination": 2,
    "inequality": 2,
    "linear_inequality": 2,
    "inequality_properties": 2,
    "linear_inequality_system": 2,
    "parallel_lines": 2,
    "perpendicular_lines": 2,
    "distance_to_line": 2,
    "three_lines_eight_angles": 2,
    "parallel_lines_j": 2,
    "parallel_lines_property": 2,
    "proposition": 2,
    "theorem_proof": 2,
    "triangle_side_relation": 2,
    "triangle_height": 2,
    "congruent": 2,
    "sss": 2,
    "sas": 2,
    "asa": 2,
    "congruent_triangles": 2,
    "sss_j": 2,
    "sas_j": 2,
    "asa_j": 2,
    "hl_j": 2,
    "isosceles_triangle_j": 2,
    "equilateral_triangle_j": 2,
    "right_triangle": 2,
    "right_triangle_j": 2,
    "pythagorean": 2,
    "pythagorean_theorem": 2,
    "rhombus": 2,
    "square_geo": 2,
    "quad_props": 2,
    "polygon_j": 2,
    "polygon_angle_sum": 2,
    "parallelogram_j": 2,
    "rectangle_j": 2,
    "rhombus_j": 2,
    "square_j": 2,
    "trapezoid_j": 2,
    "isosceles_trapezoid": 2,
    "function_concept_j": 2,
    "function_representation": 2,
    "direct_proportional_function": 2,
    "linear_function_j": 2,
    "inverse_proportional_function": 2,
    "variance_junior": 2,
    "variance_j": 2,
    "standard_deviation": 2,

    # 初三：二次方程、相似、圆、三角函数、概率统计
    "irrational_numbers": 3,
    "real_numbers": 3,
    "square_root": 3,
    "cube_root": 3,
    "arithmetic_square_root": 3,
    "irrational_number": 3,
    "real_number": 3,
    "real_number_axis": 3,
    "quadratic_radical": 3,
    "simplest_radical": 3,
    "radical_properties": 3,
    "denominator_rationalization": 3,
    "fractional_equation": 3,
    "quadratic": 3,
    "quadratic_formula": 3,
    "quadratic_equation": 3,
    "discriminant": 3,
    "vieta_theorem": 3,
    "quadratic_function_j": 3,
    "similar": 3,
    "aa_similarity": 3,
    "similar_polygons": 3,
    "similar_triangles": 3,
    "special_right": 3,
    "trig_ratio": 3,
    "sine": 3,
    "cosine": 3,
    "tangent": 3,
    "trig_ratio_def_j": 3,
    "sin_cos_tan_j": 3,
    "trig_values_30_45_60_j": 3,
    "trig_identities_j": 3,
    "solve_right_triangle_j": 3,
    "circle_theorems": 3,
    "circle_definition": 3,
    "circle_radius_diameter": 3,
    "circle_chord": 3,
    "circle_arc": 3,
    "circle_tangent": 3,
    "circle_angle_theorem": 3,
    "perpendicular_diameter": 3,
    "circle_j": 3,
    "chord_j": 3,
    "arc_j": 3,
    "central_angle": 3,
    "inscribed_angle": 3,
    "tangent_j": 3,
    "tangent_radius_perpendicular": 3,
    "triangle_centroid": 3,
    "triangle_orthocenter": 3,
    "triangle_incenter": 3,
    "triangle_circumcenter": 3,
    "set_theory": 3,
    "set_operations": 3,
    "probability": 3,
    "classical_probability": 3,
    "list_method_prob": 3,
    "tree_diagram_prob": 3,
    "permutation": 3,
    "combination": 3,
    "special_angle_30": 3,
    "special_angle_45": 3,
    "special_angle_60": 3,
    "special_angle_0_90": 3,
    # 角度制/弧度制 - 初三接触
    "angle_concept": 3,
    "initial_side": 3,
    "terminal_side": 3,
    "positive_angle": 3,
    "negative_angle": 3,
    "zero_angle": 3,
    "degree_system": 3,
    "minute_second": 3,
}

# ============================================================
# 高中节点 → 年级映射
# 依据：中国高中数学课程标准（人教版）
# ============================================================
SENIOR_NODE_GRADES = {
    # 高一：集合、函数、三角函数、数列、不等式
    "set_concept": 1,
    "set_element": 1,
    "number_sets": 1,
    "set_representation": 1,
    "subset": 1,
    "proper_subset": 1,
    "empty_set": 1,
    "intersection_set": 1,
    "union_set": 1,
    "complement_set": 1,
    "function": 1,
    "domain": 1,
    "range": 1,
    "function_concept_s": 1,
    "function_domain_s": 1,
    "function_domain_range": 1,
    "function_basic": 1,
    "function_monotonicity": 1,
    "function_monotonicity_calc": 1,
    "function_periodicity": 1,
    "function_periodicity_calc": 1,
    "function_even_odd": 1,
    "function_even_odd_s": 1,
    "function_zero_point": 1,
    "dichotomy": 1,
    "function_boundedness": 1,
    "elementary_functions": 1,
    "linear_func": 1,
    "linear_func_s": 1,
    "quadratic_func": 1,
    "quadratic_func_s": 1,
    "power_function": 1,
    "power_func": 1,
    "power_func_s": 1,
    "exponential": 1,
    "exponential_func_s": 1,
    "exponential_function": 1,
    "logarithm": 1,
    "log_func": 1,
    "log_func_s": 1,
    "logarithm_s": 1,
    "logarithmic_function": 1,
    "logarithm_operations": 1,
    "unit_circle": 1,
    "unit_circle_s": 1,
    "radian": 1,
    "radian_system": 1,
    "degree_radian_conversion": 1,
    "quadrantal_angle": 1,
    "coterminal_angle": 1,
    "trig_functions": 1,
    "trig_circ_def_s": 1,
    "trig_sign_s": 1,
    "trig_signs": 1,
    "induction_formula": 1,
    "trig_periodicity": 1,
    "trig_identities_s": 1,
    "pythagorean_identity": 1,
    "trig_reciprocal": 1,
    "trig_quotient": 1,
    "sine_def": 1,
    "cosine_def": 1,
    "tangent_def": 1,
    "cotangent_def": 1,
    "secant_def": 1,
    "cosecant_def": 1,
    "unit_circle_sin_cos": 1,
    "sin_graph": 1,
    "cos_graph": 1,
    "tan_graph": 1,
    "amplitude_transform": 1,
    "period_transform": 1,
    "phase_transform": 1,
    "general_sinusoidal": 1,
    "sequence": 1,
    "sequence_s": 1,
    "sequence_concept": 1,
    "arithmetic_seq": 1,
    "arithmetic_seq_s": 1,
    "arithmetic_sequence": 1,
    "arithmetic_formula": 1,
    "arithmetic_sum": 1,
    "arithmetic_sum_s": 1,
    "arithmetic_mean": 1,
    "geometric_seq": 1,
    "geometric_seq_s": 1,
    "geometric_sequence": 1,
    "geometric_formula": 1,
    "geometric_sum": 1,
    "geometric_sum_s": 1,
    "geometric_mean": 1,
    "sequence_summation_methods": 1,
    "inequality_relation": 1,
    "inequality_property": 1,
    "quadratic_inequality": 1,
    "mean_inequality": 1,
    "linear_programming": 1,
    "four_propositions": 1,
    "sufficient_condition": 1,
    "necessary_condition": 1,
    "necessary_sufficient_condition": 1,
    "logical_connectives": 1,
    "quantifier": 1,
    "angle_measure_s": 1,

    # 高二：解析几何、向量、概率统计、导数
    "cartesian": 2,
    "cartesian_s": 2,
    "line_eq": 2,
    "circle_eq": 2,
    "ellipse": 2,
    "hyperbola": 2,
    "parabola": 2,
    "conic": 2,
    "distance_s": 2,
    "addition_formula_s": 2,
    "sin_add": 2,
    "sin_sub": 2,
    "cos_add": 2,
    "cos_sub": 2,
    "tan_add": 2,
    "double_angle_s": 2,
    "double_angle_sin": 2,
    "double_angle_cos": 2,
    "double_angle_tan": 2,
    "half_angle_s": 2,
    "half_angle_sin": 2,
    "half_angle_cos": 2,
    "half_angle_tan": 2,
    "power_reduction": 2,
    "product_to_sum": 2,
    "sum_to_product": 2,
    "universal_substitution": 2,
    "inverse_trig": 2,
    "inverse_trig_s": 2,
    "inverse_func": 2,
    "inverse_func_s": 2,
    "composite_func": 2,
    "composite_func_s": 2,
    "trig_equations": 2,
    "trig_equation_s": 2,
    "addition_counting": 2,
    "multiplication_counting": 2,
    "math_induction": 2,
    "mathematical_induction": 2,
    "binomial": 2,
    "binomial_theorem": 2,
    "binomial_term": 2,
    "complex": 2,
    "imaginary_unit": 2,
    "complex_number": 2,
    "real_part": 2,
    "imaginary_part": 2,
    "pure_imaginary": 2,
    "complex_modulus": 2,
    "conjugate_complex": 2,
    "probability_theory": 2,
    "random_variable": 2,
    "expectation": 2,
    "variance": 2,
    "distribution": 2,
    "random_event_p": 2,
    "event_relation_p": 2,
    "probability_def_p": 2,
    "classical_prob_p": 2,
    "geometric_prob_p": 2,
    "conditional_prob_p": 2,
    "independent_events_p": 2,
    "bernoulli_trial_p": 2,
    "binomial_dist_p": 2,
    "random_variable_p": 2,
    "distribution_law_p": 2,
    "expectation_p": 2,
    "variance_p": 2,
    "conditional_probability": 2,
    "event_independence": 2,
    "probability_distribution": 2,
    "binomial_distribution": 2,
    "hypergeometric_distribution": 2,
    "variance_h": 2,
    "simple_random_sampling": 2,
    "systematic_sampling": 2,
    "stratified_sampling": 2,
    "frequency_distribution": 2,
    "scatter_plot": 2,
    "regression_line": 2,
    "inductive_reasoning": 2,
    "analogical_reasoning": 2,
    "deductive_reasoning": 2,
    "synthesis_method": 2,
    "analysis_method": 2,
    "proof_by_contradiction": 2,

    # 高三：导数、积分、空间几何、综合复习
    "limit": 3,
    "limit_concept_s": 3,
    "limit_calc_s": 3,
    "continuity": 3,
    "continuity_s": 3,
    "infinitesimal": 3,
    "infinite": 3,
    "one_sided_limit": 3,
    "derivative": 3,
    "derivative_def_s": 3,
    "derivative_rule_s": 3,
    "diff_rules": 3,
    "diff_applications": 3,
    "basic_derivative_formulas": 3,
    "derivative_product_quotient": 3,
    "monotonicity_derivative_s": 3,
    "extreme_value_s": 3,
    "max_min_s": 3,
    "differential_concept": 3,
    "integration": 3,
    "definite_integral": 3,
    "fundamental_theorem": 3,
    "integral_concept_s": 3,
    "antiderivative_s": 3,
    "indefinite_integral_s": 3,
    "definite_integral_s": 3,
    "newton_leibniz_s": 3,
    "integral_area_s": 3,
    "integral_volume_s": 3,
    "integral_geometric_meaning": 3,
    "integral_properties": 3,
    "spatial_geometry": 3,
    "plane_in_space": 3,
    "spatial_vector": 3,
    "space_coordinate": 3,
    "space_vector_operation": 3,
    "dot_product": 3,
    "cross_product": 3,
    "space_plane_equation": 3,
    "space_line_equation": 3,
    "space_line_plane": 3,
    "skew_lines": 3,
    "dihedral_angle": 3,
    "prism": 3,
    "pyramid": 3,
    "cylinder_geo": 3,
    "cone_geo": 3,
    "sphere_geo": 3,
    "surface_area_calc": 3,
    "volume_calc": 3,
    "normal_distribution": 3,
    "normal_dist_p": 3,
    "chi_square_test": 3,
    "monotonicity_s": 3,
    "even_odd_func_s": 3,
}


def get_grade_tag(node_id, level):
    """根据节点ID和level获取年级标签"""
    if level == "primary":
        grade = PRIMARY_NODE_GRADES.get(node_id)
        if grade:
            return PRIMARY_GRADE_TAGS[grade]
    elif level == "junior":
        grade = JUNIOR_NODE_GRADES.get(node_id)
        if grade:
            return JUNIOR_GRADE_TAGS[grade]
    elif level == "senior":
        grade = SENIOR_NODE_GRADES.get(node_id)
        if grade:
            return SENIOR_GRADE_TAGS[grade]
    return None


def main():
    data_path = "/Users/jia/.qclaw/workspace/math-knowledge-graph/data/core-nodes.json"

    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    nodes = data["nodes"]
    updated = 0
    skipped = 0
    not_mapped = []

    for node in nodes:
        level = node.get("level", "")
        if level not in ("primary", "junior", "senior"):
            continue

        node_id = node["id"]
        grade_tag = get_grade_tag(node_id, level)

        if grade_tag is None:
            not_mapped.append(f"{level}/{node_id} ({node['name']['zh']})")
            skipped += 1
            continue

        tags = node.get("tags", [])
        # 移除旧的年级标签（如果有）
        old_grade_tags = set(PRIMARY_GRADE_TAGS.values()) | set(JUNIOR_GRADE_TAGS.values()) | set(SENIOR_GRADE_TAGS.values())
        tags = [t for t in tags if t not in old_grade_tags]
        # 添加新年级标签
        if grade_tag not in tags:
            tags.append(grade_tag)
        node["tags"] = tags
        updated += 1

    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"✅ 已更新 {updated} 个节点的年级标签")
    print(f"⚠️  未映射 {skipped} 个节点（需手动处理）")
    if not_mapped:
        print("\n未映射节点列表：")
        for item in not_mapped:
            print(f"  - {item}")


if __name__ == "__main__":
    main()
